package.path = 'create/src/?.lua;' .. package.path
local json = require('hydronium_dom.server.json')
local h = require('hydronium').h
local ink = require('hydronium_ink')
local lab = require('hydronium_lab')
local runtime = require('hydronium_ink_lab.runtime')
local story = lab.story({id='ansi',render=function() return h(ink.Box,{flexDirection='column'},h(ink.Text,{color='red',bold=true},'ANSI 界'),h(ink.Text,{italic=true},'second row')) end,sizes={{columns=20,rows=6}}})
local r=runtime.new(lab.registry({story}))
local a=r:open('ansi')
local b=r:request({op='snapshot'})
local registry = lab.registry({lab.discovery.bind({id_prefix='wizard',path='create.stories.lua'}, dofile('create/src/create/ui/create.stories.lua'))})
local wizard = runtime.new(registry)
local f = wizard:open('wizard--install-flow', {columns=80,rows=24})
assert(f.terminal.inline and f.terminal.scrollable and f.height > 24)
assert(f.focus and #f.ansi > 0)
local down = wizard:request({op='scroll',lines=3})
local up = wizard:request({op='scroll',lines=-2})
assert(down.focus.y == f.focus.y - 3 and up.focus.y == f.focus.y - 1)
wizard:request({op='bytes',bytes='\t\t'})
local initial = wizard:request({op='snapshot'})
local jump = wizard:request({op='bytes',bytes='4'})
assert(jump.focus.token ~= initial.focus.token and jump.focus.y >= 0 and jump.focus.y < 22)
local paged = wizard:request({op='bytes',bytes='\27[5~'})
local refocus = wizard:request({op='bytes',bytes='4'})
assert(refocus.focus.token ~= paged.focus.token and refocus.focus.y >= 0 and refocus.focus.y < 22)
print(json.encode({a,b}))
