// Generates dom/types/dom/style.d.lua from the vendored CSS property data
// (css/properties.json, from mdn-data): one camelCase field per standard CSS
// property, so `style = { backgroundColor = ... }` completes and hovers with
// the property's syntax and MDN link. A property whose syntax offers bare
// keywords (`position: static | relative | ...`) lists them as completions;
// every field still accepts any HydroniumStyleValue (other strings, numbers,
// var(...), calc(...)). Kebab-case keys stay valid through the class's
// [string] index. `--check` fails when the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "../..");
const out = join(repo, "dom/types/dom/style.d.lua");
const properties = JSON.parse(readFileSync(join(here, "css/properties.json"), "utf8"));

// `display` composes its values from other productions; list the common ones.
const EXTRA_KEYWORDS = {
  display: ["none", "block", "inline", "inline-block", "flex", "inline-flex", "grid", "inline-grid", "contents", "flow-root", "list-item", "table"],
};

const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// Top-level alternatives of a CSS value syntax (split on `|` outside brackets).
function alternatives(syntax) {
  const parts = [];
  let depth = 0, current = "";
  for (let i = 0; i < syntax.length; i++) {
    const c = syntax[i];
    if ("[(<".includes(c)) depth++;
    if ("])>".includes(c)) depth--;
    if (depth === 0 && c === "|" && syntax[i - 1] === " " && syntax[i + 1] === " ") { parts.push(current.trim()); current = ""; i++; continue; }
    current += c;
  }
  parts.push(current.trim());
  return parts;
}

function keywords(name, syntax) {
  const words = alternatives(syntax).filter((part) => /^[a-z][a-z-]*$/.test(part));
  return [...new Set([...(EXTRA_KEYWORDS[name] ?? []), ...words])];
}

const lines = [
  "---@meta",
  "-- @generated by dom/webidl/css-style.mjs from mdn-data (dom/webidl/css). Do not edit.",
  "",
  "--- The `style` prop as a table: CSS properties in camelCase (kebab-case keys",
  "--- work too). Values are strings, or numbers (given `px` unless the property",
  "--- is unitless); `false`/`nil`/`\"\"` remove a property on re-render.",
  "---@class HydroniumStyle : { [string]: HydroniumStyleValue }",
];
let count = 0;
for (const [name, { syntax, mdn_url }] of Object.entries(properties)) {
  const words = keywords(name, syntax);
  const type = [...words.map((w) => JSON.stringify(w)), "HydroniumStyleValue"].join(" | ");
  const doc = `\`${syntax.replace(/`/g, "'").replace(/\s+/g, " ")}\`${mdn_url ? ` [MDN](${mdn_url})` : ""}`;
  lines.push(`---@field ${camel(name)}? ${type} ${doc}`);
  count++;
}
const text = lines.join("\n") + "\n";

if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== text) { console.error("dom/types/dom/style.d.lua is stale: run node dom/webidl/css-style.mjs"); process.exit(1); }
} else {
  writeFileSync(out, text);
  console.log(`style.d.lua: ${count} CSS properties`);
}
