local t=require("tests.runner")
local config=require("hydronium.config")
t.describe("application configuration",function()
  t.it("decodes explicit booleans and bounded integers",function()
    local value=config.require({dev={kind="boolean",default=false},port={kind="integer",min=1,max=65535}}, {dev="false",port="6311"})
    t.assert.equal(value.dev,false);t.assert.equal(value.port,6311)
  end)
  t.it("collects failures without leaking secrets",function()
    local value,errors=config.read({token={required=true},port={kind="integer",min=1,max=65535},mode={values={"dev","production"}}},{port="99999",mode="secret-value"})
    t.assert.equal(value,nil);t.assert.equal(#errors,3)
    t.assert.has_error(function()config.require({secret={kind="integer"}},{secret="do-not-echo"})end,"must be integer")
    local ok,message=pcall(config.require,{secret={kind="integer"}},{secret="do-not-echo"})
    t.assert.falsy(ok);t.assert.falsy(message:find("do-not-echo",1,true))
  end)
  t.it("supports Standard Schema transformations",function()
    local value=config.require({name={schema={["~standard"]={validate=function(input)return {value=input:upper()}end}}}},{name="moonstone"})
    t.assert.equal(value.name,"MOONSTONE")
  end)
end)
