local hosts = require("hydronium.runtime.hosts")
local contract = require("hydronium_dom.host.contract")
local dom = require("hydronium_dom.host.dom")
describe("VM-local host capabilities", function()
  it("validates versions, protects installation ownership and releases idempotently", function()
    local _, release = hosts.install("test.host", 1, { ping = function() return "first" end })
    assert.equal(hosts.require("test.host", 1).ping(), "first")
    assert.has_error(function() hosts.require("test.host", 2) end, "version mismatch")
    assert.has_error(function() hosts.install("test.host", 1, {}) end, "already installed")
    assert.truthy(release()); assert.falsy(release())
    local _, next_release = hosts.install("test.host", 1, { ping = function() return "second" end })
    assert.falsy(release()); assert.equal(hosts.require("test.host", 1).ping(), "second")
    next_release()
    assert.has_error(function() hosts.require("test.host", 1) end, "not installed")
  end)
  it("keeps separate module instances isolated and rejects invalid bindings", function()
    local a = loadfile("core/src/hydronium/runtime/hosts.lua")()
    local b = loadfile("core/src/hydronium/runtime/hosts.lua")()
    local _, release = a.install("dom", 1, { ping = function() return true end })
    assert.falsy(b.get("dom", 1)); release()
    assert.has_error(function() a.install("dom", 0, {}) end, "positive integer")
    assert.has_error(function() a.install("dom", 1, { ping = 3 }) end, "named functions")
    assert.equal(#a.describe(), 0)
  end)
  it("resolves the DOM host from its registry with no legacy globals", function()
    local bridge = {}
    for _, method in ipairs(contract.manifest().methods) do bridge[method.name] = function() end end
    bridge.create_element = function(tag) return { tag = tag } end
    local _, release = hosts.install("dom", 1, bridge)
    local ok, result = pcall(function() return dom.createDomHost().createInstance("article", {}) end)
    release()
    assert.truthy(ok); assert.equal(result.tag, "article")
  end)
  it("declares stable provider, listener effects and cleanup without function values", function()
    local manifest = contract.manifest()
    assert.equal(manifest.provider.export, "createDomBridge")
    local listener
    for _, method in ipairs(manifest.methods) do if method.name == "set_listener" then listener = method end end
    assert.equal(listener.effect, "dom.listen"); assert.equal(listener.cleanup, "remove_listener")
    assert.equal(listener.legacy_global, "__dom_set_listener")
  end)
end)
