// Tests for the overlay's Source Map v3 reader.
//
// The fixture map below is REAL output from hydronium_luax.compile on a real
// .luax component -- generated by running the compiler, not hand-written --
// so these assert against the encoder that actually feeds this decoder.

import test from "node:test";
import assert from "node:assert/strict";
import {
  decodeVlq,
  originalPositionFor,
  createSourceMapResolver,
} from "../../js/packages/dom-client/src/sourcemap.js";

// hydronium_luax.compile("local d = require(\"hydronium_dom\").d\n...", ...)
const REAL_MAP = {
  version: 3,
  file: "views/App.lua",
  sourceRoot: "",
  sources: ["views/App.luax"],
  mappings:
    "MAAM,IAAI,QAAQ,iBAAiB;AACnC,OAAO,SAAS,OAAO;QACf,GAAG,OAAO,MAAA,wBAA4B;EAC5C,OAAO;IACL,OAAO,EAAE,IAAI,KAAK,SAAS",
};

test("decodes base64 VLQ, including the sign bit", () => {
  assert.deepEqual(decodeVlq("AAAA"), [0, 0, 0, 0]);
  // 'D' is 3 -> low bit set -> -1
  assert.deepEqual(decodeVlq("D"), [-1]);
  assert.deepEqual(decodeVlq("C"), [1]);
});

test("stops rather than guessing on an unknown character", () => {
  assert.deepEqual(decodeVlq("A*A"), [0]);
});

test("resolves a generated line to its original .luax file and line", () => {
  const pos = originalPositionFor(REAL_MAP, 1);
  assert.equal(pos.file, "views/App.luax");
  assert.equal(pos.line, 1);
});

test("accumulates source line across preceding groups, not per line", () => {
  // Line 3 of the generated Lua maps to line 3 of the source in this fixture;
  // getting it right requires walking groups 1 and 2 first, because srcLine
  // deltas are cumulative across the whole map.
  const pos = originalPositionFor(REAL_MAP, 3);
  assert.equal(pos.file, "views/App.luax");
  assert.equal(pos.line, 3);
});

test("returns null past the end of the map rather than clamping", () => {
  assert.equal(originalPositionFor(REAL_MAP, 9999), null);
});

test("returns null for junk input instead of throwing", () => {
  assert.equal(originalPositionFor(null, 1), null);
  assert.equal(originalPositionFor({}, 1), null);
  assert.equal(originalPositionFor(REAL_MAP, 0), null);
  assert.equal(originalPositionFor(REAL_MAP, 1.5), null);
});

test("resolver returns a resolved frame once its map is warmed", async () => {
  const resolver = createSourceMapResolver({
    mapUrlFor: (id) => (id === "views.App" ? "/map/views.App" : null),
    fetchImpl: async () => ({ ok: true, json: async () => REAL_MAP }),
  });
  await resolver.warm(["views.App"]);
  assert.deepEqual(resolver.resolveFrame({ module: "views.App", line: 1 }), {
    file: "views/App.luax",
    line: 1,
  });
});

test("an unwarmed module stays unresolved rather than blocking", () => {
  const resolver = createSourceMapResolver({ mapUrlFor: () => "/x" });
  assert.equal(resolver.resolveFrame({ module: "never.warmed", line: 1 }), null);
});

test("a module with no map is never fetched", async () => {
  let fetched = 0;
  const resolver = createSourceMapResolver({
    mapUrlFor: () => null,
    fetchImpl: async () => { fetched += 1; return { ok: true, json: async () => ({}) }; },
  });
  await resolver.warm(["plain.lua.module"]);
  assert.equal(fetched, 0);
  assert.equal(resolver.resolveFrame({ module: "plain.lua.module", line: 2 }), null);
});

test("a failed or unparseable map never surfaces louder than the error being shown", async () => {
  const resolver = createSourceMapResolver({
    mapUrlFor: () => "/boom",
    fetchImpl: async () => { throw new Error("network down"); },
  });
  await resolver.warm(["views.App"]); // must not reject
  assert.equal(resolver.resolveFrame({ module: "views.App", line: 1 }), null);
});
