---@meta
-- WebGL 1.0 and 2.0 for Lua components, generated by dom/webidl/generate.mjs from the
-- specifications' WebIDL (dom/webidl/idl). Do not edit by hand.
-- Get a context with `canvas.context(ref, "webgl2")` (hydronium_dom.canvas). Buffers take typed arrays: `canvas.typed("Float32Array", { ... })`.

---@alias Float32List Float32Array|GLfloat[]

---@alias GLbitfield integer

---@alias GLboolean boolean

---@alias GLbyte integer

---@alias GLclampf number

---@alias GLenum integer

---@alias GLfloat number

---@alias GLint integer

---@alias GLint64 integer

---@alias GLintptr integer

---@alias GLshort integer

---@alias GLsizei integer

---@alias GLsizeiptr integer

---@alias GLubyte integer

---@alias GLuint integer

---@alias GLuint64 integer

---@alias GLushort integer

---@alias Int32List Int32Array|GLint[]

---@alias TexImageSource ImageBitmap|ImageData|HTMLImageElement|HTMLCanvasElement|HTMLVideoElement|OffscreenCanvas|any

---@alias Uint32List Uint32Array|GLuint[]

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext)
---@class WebGL2RenderingContext : WebGLRenderingContextBase, WebGL2RenderingContextBase, WebGL2RenderingContextOverloads

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext) (members shared by the interfaces that include it)
---@class WebGL2RenderingContextBase
---@field READ_BUFFER integer 0x0C02
---@field UNPACK_ROW_LENGTH integer 0x0CF2
---@field UNPACK_SKIP_ROWS integer 0x0CF3
---@field UNPACK_SKIP_PIXELS integer 0x0CF4
---@field PACK_ROW_LENGTH integer 0x0D02
---@field PACK_SKIP_ROWS integer 0x0D03
---@field PACK_SKIP_PIXELS integer 0x0D04
---@field COLOR integer 0x1800
---@field DEPTH integer 0x1801
---@field STENCIL integer 0x1802
---@field RED integer 0x1903
---@field RGB8 integer 0x8051
---@field RGB10_A2 integer 0x8059
---@field TEXTURE_BINDING_3D integer 0x806A
---@field UNPACK_SKIP_IMAGES integer 0x806D
---@field UNPACK_IMAGE_HEIGHT integer 0x806E
---@field TEXTURE_3D integer 0x806F
---@field TEXTURE_WRAP_R integer 0x8072
---@field MAX_3D_TEXTURE_SIZE integer 0x8073
---@field UNSIGNED_INT_2_10_10_10_REV integer 0x8368
---@field MAX_ELEMENTS_VERTICES integer 0x80E8
---@field MAX_ELEMENTS_INDICES integer 0x80E9
---@field TEXTURE_MIN_LOD integer 0x813A
---@field TEXTURE_MAX_LOD integer 0x813B
---@field TEXTURE_BASE_LEVEL integer 0x813C
---@field TEXTURE_MAX_LEVEL integer 0x813D
---@field MIN integer 0x8007
---@field MAX integer 0x8008
---@field DEPTH_COMPONENT24 integer 0x81A6
---@field MAX_TEXTURE_LOD_BIAS integer 0x84FD
---@field TEXTURE_COMPARE_MODE integer 0x884C
---@field TEXTURE_COMPARE_FUNC integer 0x884D
---@field CURRENT_QUERY integer 0x8865
---@field QUERY_RESULT integer 0x8866
---@field QUERY_RESULT_AVAILABLE integer 0x8867
---@field STREAM_READ integer 0x88E1
---@field STREAM_COPY integer 0x88E2
---@field STATIC_READ integer 0x88E5
---@field STATIC_COPY integer 0x88E6
---@field DYNAMIC_READ integer 0x88E9
---@field DYNAMIC_COPY integer 0x88EA
---@field MAX_DRAW_BUFFERS integer 0x8824
---@field DRAW_BUFFER0 integer 0x8825
---@field DRAW_BUFFER1 integer 0x8826
---@field DRAW_BUFFER2 integer 0x8827
---@field DRAW_BUFFER3 integer 0x8828
---@field DRAW_BUFFER4 integer 0x8829
---@field DRAW_BUFFER5 integer 0x882A
---@field DRAW_BUFFER6 integer 0x882B
---@field DRAW_BUFFER7 integer 0x882C
---@field DRAW_BUFFER8 integer 0x882D
---@field DRAW_BUFFER9 integer 0x882E
---@field DRAW_BUFFER10 integer 0x882F
---@field DRAW_BUFFER11 integer 0x8830
---@field DRAW_BUFFER12 integer 0x8831
---@field DRAW_BUFFER13 integer 0x8832
---@field DRAW_BUFFER14 integer 0x8833
---@field DRAW_BUFFER15 integer 0x8834
---@field MAX_FRAGMENT_UNIFORM_COMPONENTS integer 0x8B49
---@field MAX_VERTEX_UNIFORM_COMPONENTS integer 0x8B4A
---@field SAMPLER_3D integer 0x8B5F
---@field SAMPLER_2D_SHADOW integer 0x8B62
---@field FRAGMENT_SHADER_DERIVATIVE_HINT integer 0x8B8B
---@field PIXEL_PACK_BUFFER integer 0x88EB
---@field PIXEL_UNPACK_BUFFER integer 0x88EC
---@field PIXEL_PACK_BUFFER_BINDING integer 0x88ED
---@field PIXEL_UNPACK_BUFFER_BINDING integer 0x88EF
---@field FLOAT_MAT2x3 integer 0x8B65
---@field FLOAT_MAT2x4 integer 0x8B66
---@field FLOAT_MAT3x2 integer 0x8B67
---@field FLOAT_MAT3x4 integer 0x8B68
---@field FLOAT_MAT4x2 integer 0x8B69
---@field FLOAT_MAT4x3 integer 0x8B6A
---@field SRGB integer 0x8C40
---@field SRGB8 integer 0x8C41
---@field SRGB8_ALPHA8 integer 0x8C43
---@field COMPARE_REF_TO_TEXTURE integer 0x884E
---@field RGBA32F integer 0x8814
---@field RGB32F integer 0x8815
---@field RGBA16F integer 0x881A
---@field RGB16F integer 0x881B
---@field VERTEX_ATTRIB_ARRAY_INTEGER integer 0x88FD
---@field MAX_ARRAY_TEXTURE_LAYERS integer 0x88FF
---@field MIN_PROGRAM_TEXEL_OFFSET integer 0x8904
---@field MAX_PROGRAM_TEXEL_OFFSET integer 0x8905
---@field MAX_VARYING_COMPONENTS integer 0x8B4B
---@field TEXTURE_2D_ARRAY integer 0x8C1A
---@field TEXTURE_BINDING_2D_ARRAY integer 0x8C1D
---@field R11F_G11F_B10F integer 0x8C3A
---@field UNSIGNED_INT_10F_11F_11F_REV integer 0x8C3B
---@field RGB9_E5 integer 0x8C3D
---@field UNSIGNED_INT_5_9_9_9_REV integer 0x8C3E
---@field TRANSFORM_FEEDBACK_BUFFER_MODE integer 0x8C7F
---@field MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS integer 0x8C80
---@field TRANSFORM_FEEDBACK_VARYINGS integer 0x8C83
---@field TRANSFORM_FEEDBACK_BUFFER_START integer 0x8C84
---@field TRANSFORM_FEEDBACK_BUFFER_SIZE integer 0x8C85
---@field TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN integer 0x8C88
---@field RASTERIZER_DISCARD integer 0x8C89
---@field MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS integer 0x8C8A
---@field MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS integer 0x8C8B
---@field INTERLEAVED_ATTRIBS integer 0x8C8C
---@field SEPARATE_ATTRIBS integer 0x8C8D
---@field TRANSFORM_FEEDBACK_BUFFER integer 0x8C8E
---@field TRANSFORM_FEEDBACK_BUFFER_BINDING integer 0x8C8F
---@field RGBA32UI integer 0x8D70
---@field RGB32UI integer 0x8D71
---@field RGBA16UI integer 0x8D76
---@field RGB16UI integer 0x8D77
---@field RGBA8UI integer 0x8D7C
---@field RGB8UI integer 0x8D7D
---@field RGBA32I integer 0x8D82
---@field RGB32I integer 0x8D83
---@field RGBA16I integer 0x8D88
---@field RGB16I integer 0x8D89
---@field RGBA8I integer 0x8D8E
---@field RGB8I integer 0x8D8F
---@field RED_INTEGER integer 0x8D94
---@field RGB_INTEGER integer 0x8D98
---@field RGBA_INTEGER integer 0x8D99
---@field SAMPLER_2D_ARRAY integer 0x8DC1
---@field SAMPLER_2D_ARRAY_SHADOW integer 0x8DC4
---@field SAMPLER_CUBE_SHADOW integer 0x8DC5
---@field UNSIGNED_INT_VEC2 integer 0x8DC6
---@field UNSIGNED_INT_VEC3 integer 0x8DC7
---@field UNSIGNED_INT_VEC4 integer 0x8DC8
---@field INT_SAMPLER_2D integer 0x8DCA
---@field INT_SAMPLER_3D integer 0x8DCB
---@field INT_SAMPLER_CUBE integer 0x8DCC
---@field INT_SAMPLER_2D_ARRAY integer 0x8DCF
---@field UNSIGNED_INT_SAMPLER_2D integer 0x8DD2
---@field UNSIGNED_INT_SAMPLER_3D integer 0x8DD3
---@field UNSIGNED_INT_SAMPLER_CUBE integer 0x8DD4
---@field UNSIGNED_INT_SAMPLER_2D_ARRAY integer 0x8DD7
---@field DEPTH_COMPONENT32F integer 0x8CAC
---@field DEPTH32F_STENCIL8 integer 0x8CAD
---@field FLOAT_32_UNSIGNED_INT_24_8_REV integer 0x8DAD
---@field FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING integer 0x8210
---@field FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE integer 0x8211
---@field FRAMEBUFFER_ATTACHMENT_RED_SIZE integer 0x8212
---@field FRAMEBUFFER_ATTACHMENT_GREEN_SIZE integer 0x8213
---@field FRAMEBUFFER_ATTACHMENT_BLUE_SIZE integer 0x8214
---@field FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE integer 0x8215
---@field FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE integer 0x8216
---@field FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE integer 0x8217
---@field FRAMEBUFFER_DEFAULT integer 0x8218
---@field UNSIGNED_INT_24_8 integer 0x84FA
---@field DEPTH24_STENCIL8 integer 0x88F0
---@field UNSIGNED_NORMALIZED integer 0x8C17
---@field DRAW_FRAMEBUFFER_BINDING integer 0x8CA6
---@field READ_FRAMEBUFFER integer 0x8CA8
---@field DRAW_FRAMEBUFFER integer 0x8CA9
---@field READ_FRAMEBUFFER_BINDING integer 0x8CAA
---@field RENDERBUFFER_SAMPLES integer 0x8CAB
---@field FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER integer 0x8CD4
---@field MAX_COLOR_ATTACHMENTS integer 0x8CDF
---@field COLOR_ATTACHMENT1 integer 0x8CE1
---@field COLOR_ATTACHMENT2 integer 0x8CE2
---@field COLOR_ATTACHMENT3 integer 0x8CE3
---@field COLOR_ATTACHMENT4 integer 0x8CE4
---@field COLOR_ATTACHMENT5 integer 0x8CE5
---@field COLOR_ATTACHMENT6 integer 0x8CE6
---@field COLOR_ATTACHMENT7 integer 0x8CE7
---@field COLOR_ATTACHMENT8 integer 0x8CE8
---@field COLOR_ATTACHMENT9 integer 0x8CE9
---@field COLOR_ATTACHMENT10 integer 0x8CEA
---@field COLOR_ATTACHMENT11 integer 0x8CEB
---@field COLOR_ATTACHMENT12 integer 0x8CEC
---@field COLOR_ATTACHMENT13 integer 0x8CED
---@field COLOR_ATTACHMENT14 integer 0x8CEE
---@field COLOR_ATTACHMENT15 integer 0x8CEF
---@field FRAMEBUFFER_INCOMPLETE_MULTISAMPLE integer 0x8D56
---@field MAX_SAMPLES integer 0x8D57
---@field HALF_FLOAT integer 0x140B
---@field RG integer 0x8227
---@field RG_INTEGER integer 0x8228
---@field R8 integer 0x8229
---@field RG8 integer 0x822B
---@field R16F integer 0x822D
---@field R32F integer 0x822E
---@field RG16F integer 0x822F
---@field RG32F integer 0x8230
---@field R8I integer 0x8231
---@field R8UI integer 0x8232
---@field R16I integer 0x8233
---@field R16UI integer 0x8234
---@field R32I integer 0x8235
---@field R32UI integer 0x8236
---@field RG8I integer 0x8237
---@field RG8UI integer 0x8238
---@field RG16I integer 0x8239
---@field RG16UI integer 0x823A
---@field RG32I integer 0x823B
---@field RG32UI integer 0x823C
---@field VERTEX_ARRAY_BINDING integer 0x85B5
---@field R8_SNORM integer 0x8F94
---@field RG8_SNORM integer 0x8F95
---@field RGB8_SNORM integer 0x8F96
---@field RGBA8_SNORM integer 0x8F97
---@field SIGNED_NORMALIZED integer 0x8F9C
---@field COPY_READ_BUFFER integer 0x8F36
---@field COPY_WRITE_BUFFER integer 0x8F37
---@field COPY_READ_BUFFER_BINDING integer 0x8F36
---@field COPY_WRITE_BUFFER_BINDING integer 0x8F37
---@field UNIFORM_BUFFER integer 0x8A11
---@field UNIFORM_BUFFER_BINDING integer 0x8A28
---@field UNIFORM_BUFFER_START integer 0x8A29
---@field UNIFORM_BUFFER_SIZE integer 0x8A2A
---@field MAX_VERTEX_UNIFORM_BLOCKS integer 0x8A2B
---@field MAX_FRAGMENT_UNIFORM_BLOCKS integer 0x8A2D
---@field MAX_COMBINED_UNIFORM_BLOCKS integer 0x8A2E
---@field MAX_UNIFORM_BUFFER_BINDINGS integer 0x8A2F
---@field MAX_UNIFORM_BLOCK_SIZE integer 0x8A30
---@field MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS integer 0x8A31
---@field MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS integer 0x8A33
---@field UNIFORM_BUFFER_OFFSET_ALIGNMENT integer 0x8A34
---@field ACTIVE_UNIFORM_BLOCKS integer 0x8A36
---@field UNIFORM_TYPE integer 0x8A37
---@field UNIFORM_SIZE integer 0x8A38
---@field UNIFORM_BLOCK_INDEX integer 0x8A3A
---@field UNIFORM_OFFSET integer 0x8A3B
---@field UNIFORM_ARRAY_STRIDE integer 0x8A3C
---@field UNIFORM_MATRIX_STRIDE integer 0x8A3D
---@field UNIFORM_IS_ROW_MAJOR integer 0x8A3E
---@field UNIFORM_BLOCK_BINDING integer 0x8A3F
---@field UNIFORM_BLOCK_DATA_SIZE integer 0x8A40
---@field UNIFORM_BLOCK_ACTIVE_UNIFORMS integer 0x8A42
---@field UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES integer 0x8A43
---@field UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER integer 0x8A44
---@field UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER integer 0x8A46
---@field INVALID_INDEX integer 0xFFFFFFFF
---@field MAX_VERTEX_OUTPUT_COMPONENTS integer 0x9122
---@field MAX_FRAGMENT_INPUT_COMPONENTS integer 0x9125
---@field MAX_SERVER_WAIT_TIMEOUT integer 0x9111
---@field OBJECT_TYPE integer 0x9112
---@field SYNC_CONDITION integer 0x9113
---@field SYNC_STATUS integer 0x9114
---@field SYNC_FLAGS integer 0x9115
---@field SYNC_FENCE integer 0x9116
---@field SYNC_GPU_COMMANDS_COMPLETE integer 0x9117
---@field UNSIGNALED integer 0x9118
---@field SIGNALED integer 0x9119
---@field ALREADY_SIGNALED integer 0x911A
---@field TIMEOUT_EXPIRED integer 0x911B
---@field CONDITION_SATISFIED integer 0x911C
---@field WAIT_FAILED integer 0x911D
---@field SYNC_FLUSH_COMMANDS_BIT integer 0x00000001
---@field VERTEX_ATTRIB_ARRAY_DIVISOR integer 0x88FE
---@field ANY_SAMPLES_PASSED integer 0x8C2F
---@field ANY_SAMPLES_PASSED_CONSERVATIVE integer 0x8D6A
---@field SAMPLER_BINDING integer 0x8919
---@field RGB10_A2UI integer 0x906F
---@field INT_2_10_10_10_REV integer 0x8D9F
---@field TRANSFORM_FEEDBACK integer 0x8E22
---@field TRANSFORM_FEEDBACK_PAUSED integer 0x8E23
---@field TRANSFORM_FEEDBACK_ACTIVE integer 0x8E24
---@field TRANSFORM_FEEDBACK_BINDING integer 0x8E25
---@field TEXTURE_IMMUTABLE_FORMAT integer 0x912F
---@field MAX_ELEMENT_INDEX integer 0x8D6B
---@field TEXTURE_IMMUTABLE_LEVELS integer 0x82DF
---@field TIMEOUT_IGNORED integer -1
---@field MAX_CLIENT_WAIT_TIMEOUT_WEBGL integer 0x9247
local WebGL2RenderingContextBase = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/copyBufferSubData)
---@param readTarget GLenum
---@param writeTarget GLenum
---@param readOffset GLintptr
---@param writeOffset GLintptr
---@param size GLsizeiptr
function WebGL2RenderingContextBase:copyBufferSubData(readTarget, writeTarget, readOffset, writeOffset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getBufferSubData)
---@param target GLenum
---@param srcByteOffset GLintptr
---@param dstBuffer ArrayBufferView
---@param dstOffset? integer Default 0.
---@param length? GLuint Default 0.
function WebGL2RenderingContextBase:getBufferSubData(target, srcByteOffset, dstBuffer, dstOffset, length) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/blitFramebuffer)
---@param srcX0 GLint
---@param srcY0 GLint
---@param srcX1 GLint
---@param srcY1 GLint
---@param dstX0 GLint
---@param dstY0 GLint
---@param dstX1 GLint
---@param dstY1 GLint
---@param mask GLbitfield
---@param filter GLenum
function WebGL2RenderingContextBase:blitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/framebufferTextureLayer)
---@param target GLenum
---@param attachment GLenum
---@param texture WebGLTexture|nil
---@param level GLint
---@param layer GLint
function WebGL2RenderingContextBase:framebufferTextureLayer(target, attachment, texture, level, layer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/invalidateFramebuffer)
---@param target GLenum
---@param attachments GLenum[]
function WebGL2RenderingContextBase:invalidateFramebuffer(target, attachments) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/invalidateSubFramebuffer)
---@param target GLenum
---@param attachments GLenum[]
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
function WebGL2RenderingContextBase:invalidateSubFramebuffer(target, attachments, x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/readBuffer)
---@param src GLenum
function WebGL2RenderingContextBase:readBuffer(src) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getInternalformatParameter)
---@param target GLenum
---@param internalformat GLenum
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getInternalformatParameter(target, internalformat, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/renderbufferStorageMultisample)
---@param target GLenum
---@param samples GLsizei
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
function WebGL2RenderingContextBase:renderbufferStorageMultisample(target, samples, internalformat, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texStorage2D)
---@param target GLenum
---@param levels GLsizei
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
function WebGL2RenderingContextBase:texStorage2D(target, levels, internalformat, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texStorage3D)
---@param target GLenum
---@param levels GLsizei
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
---@param depth GLsizei
function WebGL2RenderingContextBase:texStorage3D(target, levels, internalformat, width, height, depth) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texImage3D)
---@param target GLenum
---@param level GLint
---@param internalformat GLint
---@param width GLsizei
---@param height GLsizei
---@param depth GLsizei
---@param border GLint
---@param format GLenum
---@param type GLenum
---@param pboOffset GLintptr
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, format: GLenum, type: GLenum, srcData: ArrayBufferView|nil)
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, format: GLenum, type: GLenum, srcData: ArrayBufferView, srcOffset: integer)
function WebGL2RenderingContextBase:texImage3D(target, level, internalformat, width, height, depth, border, format, type, pboOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texSubImage3D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param zoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param depth GLsizei
---@param format GLenum
---@param type GLenum
---@param pboOffset GLintptr
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, type: GLenum, srcData: ArrayBufferView|nil, srcOffset?: integer)
function WebGL2RenderingContextBase:texSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pboOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/copyTexSubImage3D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param zoffset GLint
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
function WebGL2RenderingContextBase:copyTexSubImage3D(target, level, xoffset, yoffset, zoffset, x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/compressedTexImage3D)
---@param target GLenum
---@param level GLint
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
---@param depth GLsizei
---@param border GLint
---@param imageSize GLsizei
---@param offset GLintptr
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, srcData: ArrayBufferView, srcOffset?: integer, srcLengthOverride?: GLuint)
function WebGL2RenderingContextBase:compressedTexImage3D(target, level, internalformat, width, height, depth, border, imageSize, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/compressedTexSubImage3D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param zoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param depth GLsizei
---@param format GLenum
---@param imageSize GLsizei
---@param offset GLintptr
---@overload fun(self: WebGL2RenderingContextBase, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, srcData: ArrayBufferView, srcOffset?: integer, srcLengthOverride?: GLuint)
function WebGL2RenderingContextBase:compressedTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getFragDataLocation)
---@param program WebGLProgram
---@param name string
---@return GLint
function WebGL2RenderingContextBase:getFragDataLocation(program, name) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform1ui)
---@param location WebGLUniformLocation|nil
---@param v0 GLuint
function WebGL2RenderingContextBase:uniform1ui(location, v0) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform2ui)
---@param location WebGLUniformLocation|nil
---@param v0 GLuint
---@param v1 GLuint
function WebGL2RenderingContextBase:uniform2ui(location, v0, v1) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform3ui)
---@param location WebGLUniformLocation|nil
---@param v0 GLuint
---@param v1 GLuint
---@param v2 GLuint
function WebGL2RenderingContextBase:uniform3ui(location, v0, v1, v2) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform4ui)
---@param location WebGLUniformLocation|nil
---@param v0 GLuint
---@param v1 GLuint
---@param v2 GLuint
---@param v3 GLuint
function WebGL2RenderingContextBase:uniform4ui(location, v0, v1, v2, v3) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform1uiv)
---@param location WebGLUniformLocation|nil
---@param data Uint32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniform1uiv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform2uiv)
---@param location WebGLUniformLocation|nil
---@param data Uint32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniform2uiv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform3uiv)
---@param location WebGLUniformLocation|nil
---@param data Uint32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniform3uiv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform4uiv)
---@param location WebGLUniformLocation|nil
---@param data Uint32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniform4uiv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix3x2fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix3x2fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix4x2fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix4x2fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix2x3fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix2x3fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix4x3fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix4x3fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix2x4fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix2x4fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix3x4fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextBase:uniformMatrix3x4fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribI4i)
---@param index GLuint
---@param x GLint
---@param y GLint
---@param z GLint
---@param w GLint
function WebGL2RenderingContextBase:vertexAttribI4i(index, x, y, z, w) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribI4iv)
---@param index GLuint
---@param values Int32List
function WebGL2RenderingContextBase:vertexAttribI4iv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribI4ui)
---@param index GLuint
---@param x GLuint
---@param y GLuint
---@param z GLuint
---@param w GLuint
function WebGL2RenderingContextBase:vertexAttribI4ui(index, x, y, z, w) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribI4uiv)
---@param index GLuint
---@param values Uint32List
function WebGL2RenderingContextBase:vertexAttribI4uiv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribIPointer)
---@param index GLuint
---@param size GLint
---@param type GLenum
---@param stride GLsizei
---@param offset GLintptr
function WebGL2RenderingContextBase:vertexAttribIPointer(index, size, type, stride, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/vertexAttribDivisor)
---@param index GLuint
---@param divisor GLuint
function WebGL2RenderingContextBase:vertexAttribDivisor(index, divisor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/drawArraysInstanced)
---@param mode GLenum
---@param first GLint
---@param count GLsizei
---@param instanceCount GLsizei
function WebGL2RenderingContextBase:drawArraysInstanced(mode, first, count, instanceCount) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/drawElementsInstanced)
---@param mode GLenum
---@param count GLsizei
---@param type GLenum
---@param offset GLintptr
---@param instanceCount GLsizei
function WebGL2RenderingContextBase:drawElementsInstanced(mode, count, type, offset, instanceCount) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/drawRangeElements)
---@param mode GLenum
---@param start GLuint
---@param end_ GLuint
---@param count GLsizei
---@param type GLenum
---@param offset GLintptr
function WebGL2RenderingContextBase:drawRangeElements(mode, start, end_, count, type, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/drawBuffers)
---@param buffers GLenum[]
function WebGL2RenderingContextBase:drawBuffers(buffers) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/clearBufferfv)
---@param buffer GLenum
---@param drawbuffer GLint
---@param values Float32List
---@param srcOffset? integer Default 0.
function WebGL2RenderingContextBase:clearBufferfv(buffer, drawbuffer, values, srcOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/clearBufferiv)
---@param buffer GLenum
---@param drawbuffer GLint
---@param values Int32List
---@param srcOffset? integer Default 0.
function WebGL2RenderingContextBase:clearBufferiv(buffer, drawbuffer, values, srcOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/clearBufferuiv)
---@param buffer GLenum
---@param drawbuffer GLint
---@param values Uint32List
---@param srcOffset? integer Default 0.
function WebGL2RenderingContextBase:clearBufferuiv(buffer, drawbuffer, values, srcOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/clearBufferfi)
---@param buffer GLenum
---@param drawbuffer GLint
---@param depth GLfloat
---@param stencil GLint
function WebGL2RenderingContextBase:clearBufferfi(buffer, drawbuffer, depth, stencil) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/createQuery)
---@return WebGLQuery
function WebGL2RenderingContextBase:createQuery() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/deleteQuery)
---@param query WebGLQuery|nil
function WebGL2RenderingContextBase:deleteQuery(query) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/isQuery)
---@param query WebGLQuery|nil
---@return GLboolean
function WebGL2RenderingContextBase:isQuery(query) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/beginQuery)
---@param target GLenum
---@param query WebGLQuery
function WebGL2RenderingContextBase:beginQuery(target, query) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/endQuery)
---@param target GLenum
function WebGL2RenderingContextBase:endQuery(target) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getQuery)
---@param target GLenum
---@param pname GLenum
---@return WebGLQuery|nil
function WebGL2RenderingContextBase:getQuery(target, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getQueryParameter)
---@param query WebGLQuery
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getQueryParameter(query, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/createSampler)
---@return WebGLSampler
function WebGL2RenderingContextBase:createSampler() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/deleteSampler)
---@param sampler WebGLSampler|nil
function WebGL2RenderingContextBase:deleteSampler(sampler) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/isSampler)
---@param sampler WebGLSampler|nil
---@return GLboolean
function WebGL2RenderingContextBase:isSampler(sampler) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bindSampler)
---@param unit GLuint
---@param sampler WebGLSampler|nil
function WebGL2RenderingContextBase:bindSampler(unit, sampler) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/samplerParameteri)
---@param sampler WebGLSampler
---@param pname GLenum
---@param param GLint
function WebGL2RenderingContextBase:samplerParameteri(sampler, pname, param) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/samplerParameterf)
---@param sampler WebGLSampler
---@param pname GLenum
---@param param GLfloat
function WebGL2RenderingContextBase:samplerParameterf(sampler, pname, param) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getSamplerParameter)
---@param sampler WebGLSampler
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getSamplerParameter(sampler, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/fenceSync)
---@param condition GLenum
---@param flags GLbitfield
---@return WebGLSync|nil
function WebGL2RenderingContextBase:fenceSync(condition, flags) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/isSync)
---@param sync WebGLSync|nil
---@return GLboolean
function WebGL2RenderingContextBase:isSync(sync) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/deleteSync)
---@param sync WebGLSync|nil
function WebGL2RenderingContextBase:deleteSync(sync) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/clientWaitSync)
---@param sync WebGLSync
---@param flags GLbitfield
---@param timeout GLuint64
---@return GLenum
function WebGL2RenderingContextBase:clientWaitSync(sync, flags, timeout) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/waitSync)
---@param sync WebGLSync
---@param flags GLbitfield
---@param timeout GLint64
function WebGL2RenderingContextBase:waitSync(sync, flags, timeout) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getSyncParameter)
---@param sync WebGLSync
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getSyncParameter(sync, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/createTransformFeedback)
---@return WebGLTransformFeedback
function WebGL2RenderingContextBase:createTransformFeedback() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/deleteTransformFeedback)
---@param tf WebGLTransformFeedback|nil
function WebGL2RenderingContextBase:deleteTransformFeedback(tf) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/isTransformFeedback)
---@param tf WebGLTransformFeedback|nil
---@return GLboolean
function WebGL2RenderingContextBase:isTransformFeedback(tf) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bindTransformFeedback)
---@param target GLenum
---@param tf WebGLTransformFeedback|nil
function WebGL2RenderingContextBase:bindTransformFeedback(target, tf) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/beginTransformFeedback)
---@param primitiveMode GLenum
function WebGL2RenderingContextBase:beginTransformFeedback(primitiveMode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/endTransformFeedback)
function WebGL2RenderingContextBase:endTransformFeedback() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/transformFeedbackVaryings)
---@param program WebGLProgram
---@param varyings string[]
---@param bufferMode GLenum
function WebGL2RenderingContextBase:transformFeedbackVaryings(program, varyings, bufferMode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getTransformFeedbackVarying)
---@param program WebGLProgram
---@param index GLuint
---@return WebGLActiveInfo|nil
function WebGL2RenderingContextBase:getTransformFeedbackVarying(program, index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/pauseTransformFeedback)
function WebGL2RenderingContextBase:pauseTransformFeedback() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/resumeTransformFeedback)
function WebGL2RenderingContextBase:resumeTransformFeedback() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bindBufferBase)
---@param target GLenum
---@param index GLuint
---@param buffer WebGLBuffer|nil
function WebGL2RenderingContextBase:bindBufferBase(target, index, buffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bindBufferRange)
---@param target GLenum
---@param index GLuint
---@param buffer WebGLBuffer|nil
---@param offset GLintptr
---@param size GLsizeiptr
function WebGL2RenderingContextBase:bindBufferRange(target, index, buffer, offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getIndexedParameter)
---@param target GLenum
---@param index GLuint
---@return any
function WebGL2RenderingContextBase:getIndexedParameter(target, index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getUniformIndices)
---@param program WebGLProgram
---@param uniformNames string[]
---@return GLuint[]|nil
function WebGL2RenderingContextBase:getUniformIndices(program, uniformNames) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getActiveUniforms)
---@param program WebGLProgram
---@param uniformIndices GLuint[]
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getActiveUniforms(program, uniformIndices, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getUniformBlockIndex)
---@param program WebGLProgram
---@param uniformBlockName string
---@return GLuint
function WebGL2RenderingContextBase:getUniformBlockIndex(program, uniformBlockName) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getActiveUniformBlockParameter)
---@param program WebGLProgram
---@param uniformBlockIndex GLuint
---@param pname GLenum
---@return any
function WebGL2RenderingContextBase:getActiveUniformBlockParameter(program, uniformBlockIndex, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/getActiveUniformBlockName)
---@param program WebGLProgram
---@param uniformBlockIndex GLuint
---@return string|nil
function WebGL2RenderingContextBase:getActiveUniformBlockName(program, uniformBlockIndex) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformBlockBinding)
---@param program WebGLProgram
---@param uniformBlockIndex GLuint
---@param uniformBlockBinding GLuint
function WebGL2RenderingContextBase:uniformBlockBinding(program, uniformBlockIndex, uniformBlockBinding) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/createVertexArray)
---@return WebGLVertexArrayObject
function WebGL2RenderingContextBase:createVertexArray() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/deleteVertexArray)
---@param vertexArray WebGLVertexArrayObject|nil
function WebGL2RenderingContextBase:deleteVertexArray(vertexArray) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/isVertexArray)
---@param vertexArray WebGLVertexArrayObject|nil
---@return GLboolean
function WebGL2RenderingContextBase:isVertexArray(vertexArray) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bindVertexArray)
---@param array WebGLVertexArrayObject|nil
function WebGL2RenderingContextBase:bindVertexArray(array) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext) (members shared by the interfaces that include it)
---@class WebGL2RenderingContextOverloads
local WebGL2RenderingContextOverloads = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bufferData)
---@param target GLenum
---@param size GLsizeiptr
---@param usage GLenum
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, srcData: AllowSharedBufferSource|nil, usage: GLenum)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, srcData: ArrayBufferView, usage: GLenum, srcOffset: integer, length?: GLuint)
function WebGL2RenderingContextOverloads:bufferData(target, size, usage) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/bufferSubData)
---@param target GLenum
---@param dstByteOffset GLintptr
---@param srcData AllowSharedBufferSource
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, dstByteOffset: GLintptr, srcData: ArrayBufferView, srcOffset: integer, length?: GLuint)
function WebGL2RenderingContextOverloads:bufferSubData(target, dstByteOffset, srcData) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texImage2D)
---@param target GLenum
---@param level GLint
---@param internalformat GLint
---@param width GLsizei
---@param height GLsizei
---@param border GLint
---@param format GLenum
---@param type GLenum
---@param pixels ArrayBufferView|nil
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLint, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type: GLenum, pboOffset: GLintptr)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type: GLenum, srcData: ArrayBufferView, srcOffset: integer)
function WebGL2RenderingContextOverloads:texImage2D(target, level, internalformat, width, height, border, format, type, pixels) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/texSubImage2D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param type GLenum
---@param pixels ArrayBufferView|nil
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, type: GLenum, pboOffset: GLintptr)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, type: GLenum, source: TexImageSource)
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, type: GLenum, srcData: ArrayBufferView, srcOffset: integer)
function WebGL2RenderingContextOverloads:texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/compressedTexImage2D)
---@param target GLenum
---@param level GLint
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
---@param border GLint
---@param imageSize GLsizei
---@param offset GLintptr
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, border: GLint, srcData: ArrayBufferView, srcOffset?: integer, srcLengthOverride?: GLuint)
function WebGL2RenderingContextOverloads:compressedTexImage2D(target, level, internalformat, width, height, border, imageSize, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/compressedTexSubImage2D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param imageSize GLsizei
---@param offset GLintptr
---@overload fun(self: WebGL2RenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, srcData: ArrayBufferView, srcOffset?: integer, srcLengthOverride?: GLuint)
function WebGL2RenderingContextOverloads:compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform1fv)
---@param location WebGLUniformLocation|nil
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform1fv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform2fv)
---@param location WebGLUniformLocation|nil
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform2fv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform3fv)
---@param location WebGLUniformLocation|nil
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform3fv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform4fv)
---@param location WebGLUniformLocation|nil
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform4fv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform1iv)
---@param location WebGLUniformLocation|nil
---@param data Int32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform1iv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform2iv)
---@param location WebGLUniformLocation|nil
---@param data Int32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform2iv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform3iv)
---@param location WebGLUniformLocation|nil
---@param data Int32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform3iv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniform4iv)
---@param location WebGLUniformLocation|nil
---@param data Int32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniform4iv(location, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix2fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniformMatrix2fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix3fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniformMatrix3fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/uniformMatrix4fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param data Float32List
---@param srcOffset? integer Default 0.
---@param srcLength? GLuint Default 0.
function WebGL2RenderingContextOverloads:uniformMatrix4fv(location, transpose, data, srcOffset, srcLength) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGL2RenderingContext/readPixels)
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param type GLenum
---@param dstData ArrayBufferView|nil
---@overload fun(self: WebGL2RenderingContextOverloads, x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, type: GLenum, offset: GLintptr)
---@overload fun(self: WebGL2RenderingContextOverloads, x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, type: GLenum, dstData: ArrayBufferView, dstOffset: integer)
function WebGL2RenderingContextOverloads:readPixels(x, y, width, height, format, type, dstData) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLActiveInfo)
---@class WebGLActiveInfo
---@field size GLint Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLActiveInfo/size)
---@field type GLenum Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLActiveInfo/type)
---@field name string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLActiveInfo/name)

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLBuffer)
---@class WebGLBuffer : WebGLObject

---@class WebGLContextAttributes
---@field alpha? boolean Default true.
---@field depth? boolean Default true.
---@field stencil? boolean Default false.
---@field antialias? boolean Default true.
---@field premultipliedAlpha? boolean Default true.
---@field preserveDrawingBuffer? boolean Default false.
---@field powerPreference? WebGLPowerPreference Default "default".
---@field failIfMajorPerformanceCaveat? boolean Default false.
---@field desynchronized? boolean Default false.

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLContextEvent)
---@class WebGLContextEvent
---@field statusMessage string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLContextEvent/statusMessage)

---@class WebGLContextEventInit
---@field statusMessage? string Default "".

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLFramebuffer)
---@class WebGLFramebuffer : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLObject)
---@class WebGLObject
---@field label string [MDN](https://developer.mozilla.org/docs/Web/API/WebGLObject/label)

---@alias WebGLPowerPreference
---| "default"
---| "low-power"
---| "high-performance"

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLProgram)
---@class WebGLProgram : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLQuery)
---@class WebGLQuery : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderbuffer)
---@class WebGLRenderbuffer : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext)
---@class WebGLRenderingContext : WebGLRenderingContextBase, WebGLRenderingContextOverloads

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext) (members shared by the interfaces that include it)
---@class WebGLRenderingContextBase
---@field DEPTH_BUFFER_BIT integer 0x00000100
---@field STENCIL_BUFFER_BIT integer 0x00000400
---@field COLOR_BUFFER_BIT integer 0x00004000
---@field POINTS integer 0x0000
---@field LINES integer 0x0001
---@field LINE_LOOP integer 0x0002
---@field LINE_STRIP integer 0x0003
---@field TRIANGLES integer 0x0004
---@field TRIANGLE_STRIP integer 0x0005
---@field TRIANGLE_FAN integer 0x0006
---@field ZERO integer 0
---@field ONE integer 1
---@field SRC_COLOR integer 0x0300
---@field ONE_MINUS_SRC_COLOR integer 0x0301
---@field SRC_ALPHA integer 0x0302
---@field ONE_MINUS_SRC_ALPHA integer 0x0303
---@field DST_ALPHA integer 0x0304
---@field ONE_MINUS_DST_ALPHA integer 0x0305
---@field DST_COLOR integer 0x0306
---@field ONE_MINUS_DST_COLOR integer 0x0307
---@field SRC_ALPHA_SATURATE integer 0x0308
---@field FUNC_ADD integer 0x8006
---@field BLEND_EQUATION integer 0x8009
---@field BLEND_EQUATION_RGB integer 0x8009
---@field BLEND_EQUATION_ALPHA integer 0x883D
---@field FUNC_SUBTRACT integer 0x800A
---@field FUNC_REVERSE_SUBTRACT integer 0x800B
---@field BLEND_DST_RGB integer 0x80C8
---@field BLEND_SRC_RGB integer 0x80C9
---@field BLEND_DST_ALPHA integer 0x80CA
---@field BLEND_SRC_ALPHA integer 0x80CB
---@field CONSTANT_COLOR integer 0x8001
---@field ONE_MINUS_CONSTANT_COLOR integer 0x8002
---@field CONSTANT_ALPHA integer 0x8003
---@field ONE_MINUS_CONSTANT_ALPHA integer 0x8004
---@field BLEND_COLOR integer 0x8005
---@field ARRAY_BUFFER integer 0x8892
---@field ELEMENT_ARRAY_BUFFER integer 0x8893
---@field ARRAY_BUFFER_BINDING integer 0x8894
---@field ELEMENT_ARRAY_BUFFER_BINDING integer 0x8895
---@field STREAM_DRAW integer 0x88E0
---@field STATIC_DRAW integer 0x88E4
---@field DYNAMIC_DRAW integer 0x88E8
---@field BUFFER_SIZE integer 0x8764
---@field BUFFER_USAGE integer 0x8765
---@field CURRENT_VERTEX_ATTRIB integer 0x8626
---@field FRONT integer 0x0404
---@field BACK integer 0x0405
---@field FRONT_AND_BACK integer 0x0408
---@field CULL_FACE integer 0x0B44
---@field BLEND integer 0x0BE2
---@field DITHER integer 0x0BD0
---@field STENCIL_TEST integer 0x0B90
---@field DEPTH_TEST integer 0x0B71
---@field SCISSOR_TEST integer 0x0C11
---@field POLYGON_OFFSET_FILL integer 0x8037
---@field SAMPLE_ALPHA_TO_COVERAGE integer 0x809E
---@field SAMPLE_COVERAGE integer 0x80A0
---@field NO_ERROR integer 0
---@field INVALID_ENUM integer 0x0500
---@field INVALID_VALUE integer 0x0501
---@field INVALID_OPERATION integer 0x0502
---@field OUT_OF_MEMORY integer 0x0505
---@field CW integer 0x0900
---@field CCW integer 0x0901
---@field LINE_WIDTH integer 0x0B21
---@field ALIASED_POINT_SIZE_RANGE integer 0x846D
---@field ALIASED_LINE_WIDTH_RANGE integer 0x846E
---@field CULL_FACE_MODE integer 0x0B45
---@field FRONT_FACE integer 0x0B46
---@field DEPTH_RANGE integer 0x0B70
---@field DEPTH_WRITEMASK integer 0x0B72
---@field DEPTH_CLEAR_VALUE integer 0x0B73
---@field DEPTH_FUNC integer 0x0B74
---@field STENCIL_CLEAR_VALUE integer 0x0B91
---@field STENCIL_FUNC integer 0x0B92
---@field STENCIL_FAIL integer 0x0B94
---@field STENCIL_PASS_DEPTH_FAIL integer 0x0B95
---@field STENCIL_PASS_DEPTH_PASS integer 0x0B96
---@field STENCIL_REF integer 0x0B97
---@field STENCIL_VALUE_MASK integer 0x0B93
---@field STENCIL_WRITEMASK integer 0x0B98
---@field STENCIL_BACK_FUNC integer 0x8800
---@field STENCIL_BACK_FAIL integer 0x8801
---@field STENCIL_BACK_PASS_DEPTH_FAIL integer 0x8802
---@field STENCIL_BACK_PASS_DEPTH_PASS integer 0x8803
---@field STENCIL_BACK_REF integer 0x8CA3
---@field STENCIL_BACK_VALUE_MASK integer 0x8CA4
---@field STENCIL_BACK_WRITEMASK integer 0x8CA5
---@field VIEWPORT integer 0x0BA2
---@field SCISSOR_BOX integer 0x0C10
---@field COLOR_CLEAR_VALUE integer 0x0C22
---@field COLOR_WRITEMASK integer 0x0C23
---@field UNPACK_ALIGNMENT integer 0x0CF5
---@field PACK_ALIGNMENT integer 0x0D05
---@field MAX_TEXTURE_SIZE integer 0x0D33
---@field MAX_VIEWPORT_DIMS integer 0x0D3A
---@field SUBPIXEL_BITS integer 0x0D50
---@field RED_BITS integer 0x0D52
---@field GREEN_BITS integer 0x0D53
---@field BLUE_BITS integer 0x0D54
---@field ALPHA_BITS integer 0x0D55
---@field DEPTH_BITS integer 0x0D56
---@field STENCIL_BITS integer 0x0D57
---@field POLYGON_OFFSET_UNITS integer 0x2A00
---@field POLYGON_OFFSET_FACTOR integer 0x8038
---@field TEXTURE_BINDING_2D integer 0x8069
---@field SAMPLE_BUFFERS integer 0x80A8
---@field SAMPLES integer 0x80A9
---@field SAMPLE_COVERAGE_VALUE integer 0x80AA
---@field SAMPLE_COVERAGE_INVERT integer 0x80AB
---@field COMPRESSED_TEXTURE_FORMATS integer 0x86A3
---@field DONT_CARE integer 0x1100
---@field FASTEST integer 0x1101
---@field NICEST integer 0x1102
---@field GENERATE_MIPMAP_HINT integer 0x8192
---@field BYTE integer 0x1400
---@field UNSIGNED_BYTE integer 0x1401
---@field SHORT integer 0x1402
---@field UNSIGNED_SHORT integer 0x1403
---@field INT integer 0x1404
---@field UNSIGNED_INT integer 0x1405
---@field FLOAT integer 0x1406
---@field DEPTH_COMPONENT integer 0x1902
---@field ALPHA integer 0x1906
---@field RGB integer 0x1907
---@field RGBA integer 0x1908
---@field LUMINANCE integer 0x1909
---@field LUMINANCE_ALPHA integer 0x190A
---@field UNSIGNED_SHORT_4_4_4_4 integer 0x8033
---@field UNSIGNED_SHORT_5_5_5_1 integer 0x8034
---@field UNSIGNED_SHORT_5_6_5 integer 0x8363
---@field FRAGMENT_SHADER integer 0x8B30
---@field VERTEX_SHADER integer 0x8B31
---@field MAX_VERTEX_ATTRIBS integer 0x8869
---@field MAX_VERTEX_UNIFORM_VECTORS integer 0x8DFB
---@field MAX_VARYING_VECTORS integer 0x8DFC
---@field MAX_COMBINED_TEXTURE_IMAGE_UNITS integer 0x8B4D
---@field MAX_VERTEX_TEXTURE_IMAGE_UNITS integer 0x8B4C
---@field MAX_TEXTURE_IMAGE_UNITS integer 0x8872
---@field MAX_FRAGMENT_UNIFORM_VECTORS integer 0x8DFD
---@field SHADER_TYPE integer 0x8B4F
---@field DELETE_STATUS integer 0x8B80
---@field LINK_STATUS integer 0x8B82
---@field VALIDATE_STATUS integer 0x8B83
---@field ATTACHED_SHADERS integer 0x8B85
---@field ACTIVE_UNIFORMS integer 0x8B86
---@field ACTIVE_ATTRIBUTES integer 0x8B89
---@field SHADING_LANGUAGE_VERSION integer 0x8B8C
---@field CURRENT_PROGRAM integer 0x8B8D
---@field NEVER integer 0x0200
---@field LESS integer 0x0201
---@field EQUAL integer 0x0202
---@field LEQUAL integer 0x0203
---@field GREATER integer 0x0204
---@field NOTEQUAL integer 0x0205
---@field GEQUAL integer 0x0206
---@field ALWAYS integer 0x0207
---@field KEEP integer 0x1E00
---@field REPLACE integer 0x1E01
---@field INCR integer 0x1E02
---@field DECR integer 0x1E03
---@field INVERT integer 0x150A
---@field INCR_WRAP integer 0x8507
---@field DECR_WRAP integer 0x8508
---@field VENDOR integer 0x1F00
---@field RENDERER integer 0x1F01
---@field VERSION integer 0x1F02
---@field NEAREST integer 0x2600
---@field LINEAR integer 0x2601
---@field NEAREST_MIPMAP_NEAREST integer 0x2700
---@field LINEAR_MIPMAP_NEAREST integer 0x2701
---@field NEAREST_MIPMAP_LINEAR integer 0x2702
---@field LINEAR_MIPMAP_LINEAR integer 0x2703
---@field TEXTURE_MAG_FILTER integer 0x2800
---@field TEXTURE_MIN_FILTER integer 0x2801
---@field TEXTURE_WRAP_S integer 0x2802
---@field TEXTURE_WRAP_T integer 0x2803
---@field TEXTURE_2D integer 0x0DE1
---@field TEXTURE integer 0x1702
---@field TEXTURE_CUBE_MAP integer 0x8513
---@field TEXTURE_BINDING_CUBE_MAP integer 0x8514
---@field TEXTURE_CUBE_MAP_POSITIVE_X integer 0x8515
---@field TEXTURE_CUBE_MAP_NEGATIVE_X integer 0x8516
---@field TEXTURE_CUBE_MAP_POSITIVE_Y integer 0x8517
---@field TEXTURE_CUBE_MAP_NEGATIVE_Y integer 0x8518
---@field TEXTURE_CUBE_MAP_POSITIVE_Z integer 0x8519
---@field TEXTURE_CUBE_MAP_NEGATIVE_Z integer 0x851A
---@field MAX_CUBE_MAP_TEXTURE_SIZE integer 0x851C
---@field TEXTURE0 integer 0x84C0
---@field TEXTURE1 integer 0x84C1
---@field TEXTURE2 integer 0x84C2
---@field TEXTURE3 integer 0x84C3
---@field TEXTURE4 integer 0x84C4
---@field TEXTURE5 integer 0x84C5
---@field TEXTURE6 integer 0x84C6
---@field TEXTURE7 integer 0x84C7
---@field TEXTURE8 integer 0x84C8
---@field TEXTURE9 integer 0x84C9
---@field TEXTURE10 integer 0x84CA
---@field TEXTURE11 integer 0x84CB
---@field TEXTURE12 integer 0x84CC
---@field TEXTURE13 integer 0x84CD
---@field TEXTURE14 integer 0x84CE
---@field TEXTURE15 integer 0x84CF
---@field TEXTURE16 integer 0x84D0
---@field TEXTURE17 integer 0x84D1
---@field TEXTURE18 integer 0x84D2
---@field TEXTURE19 integer 0x84D3
---@field TEXTURE20 integer 0x84D4
---@field TEXTURE21 integer 0x84D5
---@field TEXTURE22 integer 0x84D6
---@field TEXTURE23 integer 0x84D7
---@field TEXTURE24 integer 0x84D8
---@field TEXTURE25 integer 0x84D9
---@field TEXTURE26 integer 0x84DA
---@field TEXTURE27 integer 0x84DB
---@field TEXTURE28 integer 0x84DC
---@field TEXTURE29 integer 0x84DD
---@field TEXTURE30 integer 0x84DE
---@field TEXTURE31 integer 0x84DF
---@field ACTIVE_TEXTURE integer 0x84E0
---@field REPEAT integer 0x2901
---@field CLAMP_TO_EDGE integer 0x812F
---@field MIRRORED_REPEAT integer 0x8370
---@field FLOAT_VEC2 integer 0x8B50
---@field FLOAT_VEC3 integer 0x8B51
---@field FLOAT_VEC4 integer 0x8B52
---@field INT_VEC2 integer 0x8B53
---@field INT_VEC3 integer 0x8B54
---@field INT_VEC4 integer 0x8B55
---@field BOOL integer 0x8B56
---@field BOOL_VEC2 integer 0x8B57
---@field BOOL_VEC3 integer 0x8B58
---@field BOOL_VEC4 integer 0x8B59
---@field FLOAT_MAT2 integer 0x8B5A
---@field FLOAT_MAT3 integer 0x8B5B
---@field FLOAT_MAT4 integer 0x8B5C
---@field SAMPLER_2D integer 0x8B5E
---@field SAMPLER_CUBE integer 0x8B60
---@field VERTEX_ATTRIB_ARRAY_ENABLED integer 0x8622
---@field VERTEX_ATTRIB_ARRAY_SIZE integer 0x8623
---@field VERTEX_ATTRIB_ARRAY_STRIDE integer 0x8624
---@field VERTEX_ATTRIB_ARRAY_TYPE integer 0x8625
---@field VERTEX_ATTRIB_ARRAY_NORMALIZED integer 0x886A
---@field VERTEX_ATTRIB_ARRAY_POINTER integer 0x8645
---@field VERTEX_ATTRIB_ARRAY_BUFFER_BINDING integer 0x889F
---@field IMPLEMENTATION_COLOR_READ_TYPE integer 0x8B9A
---@field IMPLEMENTATION_COLOR_READ_FORMAT integer 0x8B9B
---@field COMPILE_STATUS integer 0x8B81
---@field LOW_FLOAT integer 0x8DF0
---@field MEDIUM_FLOAT integer 0x8DF1
---@field HIGH_FLOAT integer 0x8DF2
---@field LOW_INT integer 0x8DF3
---@field MEDIUM_INT integer 0x8DF4
---@field HIGH_INT integer 0x8DF5
---@field FRAMEBUFFER integer 0x8D40
---@field RENDERBUFFER integer 0x8D41
---@field RGBA4 integer 0x8056
---@field RGB5_A1 integer 0x8057
---@field RGBA8 integer 0x8058
---@field RGB565 integer 0x8D62
---@field DEPTH_COMPONENT16 integer 0x81A5
---@field STENCIL_INDEX8 integer 0x8D48
---@field DEPTH_STENCIL integer 0x84F9
---@field RENDERBUFFER_WIDTH integer 0x8D42
---@field RENDERBUFFER_HEIGHT integer 0x8D43
---@field RENDERBUFFER_INTERNAL_FORMAT integer 0x8D44
---@field RENDERBUFFER_RED_SIZE integer 0x8D50
---@field RENDERBUFFER_GREEN_SIZE integer 0x8D51
---@field RENDERBUFFER_BLUE_SIZE integer 0x8D52
---@field RENDERBUFFER_ALPHA_SIZE integer 0x8D53
---@field RENDERBUFFER_DEPTH_SIZE integer 0x8D54
---@field RENDERBUFFER_STENCIL_SIZE integer 0x8D55
---@field FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE integer 0x8CD0
---@field FRAMEBUFFER_ATTACHMENT_OBJECT_NAME integer 0x8CD1
---@field FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL integer 0x8CD2
---@field FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE integer 0x8CD3
---@field COLOR_ATTACHMENT0 integer 0x8CE0
---@field DEPTH_ATTACHMENT integer 0x8D00
---@field STENCIL_ATTACHMENT integer 0x8D20
---@field DEPTH_STENCIL_ATTACHMENT integer 0x821A
---@field NONE integer 0
---@field FRAMEBUFFER_COMPLETE integer 0x8CD5
---@field FRAMEBUFFER_INCOMPLETE_ATTACHMENT integer 0x8CD6
---@field FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT integer 0x8CD7
---@field FRAMEBUFFER_INCOMPLETE_DIMENSIONS integer 0x8CD9
---@field FRAMEBUFFER_UNSUPPORTED integer 0x8CDD
---@field FRAMEBUFFER_BINDING integer 0x8CA6
---@field RENDERBUFFER_BINDING integer 0x8CA7
---@field MAX_RENDERBUFFER_SIZE integer 0x84E8
---@field INVALID_FRAMEBUFFER_OPERATION integer 0x0506
---@field UNPACK_FLIP_Y_WEBGL integer 0x9240
---@field UNPACK_PREMULTIPLY_ALPHA_WEBGL integer 0x9241
---@field CONTEXT_LOST_WEBGL integer 0x9242
---@field UNPACK_COLORSPACE_CONVERSION_WEBGL integer 0x9243
---@field BROWSER_DEFAULT_WEBGL integer 0x9244
---@field canvas HTMLCanvasElement|OffscreenCanvas Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/canvas)
---@field drawingBufferWidth GLsizei Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawingBufferWidth)
---@field drawingBufferHeight GLsizei Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawingBufferHeight)
---@field drawingBufferFormat GLenum Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawingBufferFormat)
---@field drawingBufferColorSpace PredefinedColorSpace [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawingBufferColorSpace)
---@field unpackColorSpace PredefinedColorSpace [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/unpackColorSpace)
local WebGLRenderingContextBase = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getContextAttributes)
---@return WebGLContextAttributes|nil
function WebGLRenderingContextBase:getContextAttributes() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isContextLost)
---@return boolean
function WebGLRenderingContextBase:isContextLost() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getSupportedExtensions)
---@return string[]|nil
function WebGLRenderingContextBase:getSupportedExtensions() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getExtension)
---@param name string
---@return any
function WebGLRenderingContextBase:getExtension(name) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawingBufferStorage)
---@param sizedFormat GLenum
---@param width integer
---@param height integer
function WebGLRenderingContextBase:drawingBufferStorage(sizedFormat, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/activeTexture)
---@param texture GLenum
function WebGLRenderingContextBase:activeTexture(texture) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/attachShader)
---@param program WebGLProgram
---@param shader WebGLShader
function WebGLRenderingContextBase:attachShader(program, shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bindAttribLocation)
---@param program WebGLProgram
---@param index GLuint
---@param name string
function WebGLRenderingContextBase:bindAttribLocation(program, index, name) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bindBuffer)
---@param target GLenum
---@param buffer WebGLBuffer|nil
function WebGLRenderingContextBase:bindBuffer(target, buffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bindFramebuffer)
---@param target GLenum
---@param framebuffer WebGLFramebuffer|nil
function WebGLRenderingContextBase:bindFramebuffer(target, framebuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bindRenderbuffer)
---@param target GLenum
---@param renderbuffer WebGLRenderbuffer|nil
function WebGLRenderingContextBase:bindRenderbuffer(target, renderbuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bindTexture)
---@param target GLenum
---@param texture WebGLTexture|nil
function WebGLRenderingContextBase:bindTexture(target, texture) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/blendColor)
---@param red GLclampf
---@param green GLclampf
---@param blue GLclampf
---@param alpha GLclampf
function WebGLRenderingContextBase:blendColor(red, green, blue, alpha) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/blendEquation)
---@param mode GLenum
function WebGLRenderingContextBase:blendEquation(mode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/blendEquationSeparate)
---@param modeRGB GLenum
---@param modeAlpha GLenum
function WebGLRenderingContextBase:blendEquationSeparate(modeRGB, modeAlpha) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/blendFunc)
---@param sfactor GLenum
---@param dfactor GLenum
function WebGLRenderingContextBase:blendFunc(sfactor, dfactor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/blendFuncSeparate)
---@param srcRGB GLenum
---@param dstRGB GLenum
---@param srcAlpha GLenum
---@param dstAlpha GLenum
function WebGLRenderingContextBase:blendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/checkFramebufferStatus)
---@param target GLenum
---@return GLenum
function WebGLRenderingContextBase:checkFramebufferStatus(target) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/clear)
---@param mask GLbitfield
function WebGLRenderingContextBase:clear(mask) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/clearColor)
---@param red GLclampf
---@param green GLclampf
---@param blue GLclampf
---@param alpha GLclampf
function WebGLRenderingContextBase:clearColor(red, green, blue, alpha) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/clearDepth)
---@param depth GLclampf
function WebGLRenderingContextBase:clearDepth(depth) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/clearStencil)
---@param s GLint
function WebGLRenderingContextBase:clearStencil(s) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/colorMask)
---@param red GLboolean
---@param green GLboolean
---@param blue GLboolean
---@param alpha GLboolean
function WebGLRenderingContextBase:colorMask(red, green, blue, alpha) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/compileShader)
---@param shader WebGLShader
function WebGLRenderingContextBase:compileShader(shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/copyTexImage2D)
---@param target GLenum
---@param level GLint
---@param internalformat GLenum
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
---@param border GLint
function WebGLRenderingContextBase:copyTexImage2D(target, level, internalformat, x, y, width, height, border) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/copyTexSubImage2D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
function WebGLRenderingContextBase:copyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createBuffer)
---@return WebGLBuffer
function WebGLRenderingContextBase:createBuffer() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createFramebuffer)
---@return WebGLFramebuffer
function WebGLRenderingContextBase:createFramebuffer() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createProgram)
---@return WebGLProgram
function WebGLRenderingContextBase:createProgram() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createRenderbuffer)
---@return WebGLRenderbuffer
function WebGLRenderingContextBase:createRenderbuffer() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createShader)
---@param type GLenum
---@return WebGLShader|nil
function WebGLRenderingContextBase:createShader(type) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/createTexture)
---@return WebGLTexture
function WebGLRenderingContextBase:createTexture() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/cullFace)
---@param mode GLenum
function WebGLRenderingContextBase:cullFace(mode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteBuffer)
---@param buffer WebGLBuffer|nil
function WebGLRenderingContextBase:deleteBuffer(buffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteFramebuffer)
---@param framebuffer WebGLFramebuffer|nil
function WebGLRenderingContextBase:deleteFramebuffer(framebuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteProgram)
---@param program WebGLProgram|nil
function WebGLRenderingContextBase:deleteProgram(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteRenderbuffer)
---@param renderbuffer WebGLRenderbuffer|nil
function WebGLRenderingContextBase:deleteRenderbuffer(renderbuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteShader)
---@param shader WebGLShader|nil
function WebGLRenderingContextBase:deleteShader(shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/deleteTexture)
---@param texture WebGLTexture|nil
function WebGLRenderingContextBase:deleteTexture(texture) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/depthFunc)
---@param func GLenum
function WebGLRenderingContextBase:depthFunc(func) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/depthMask)
---@param flag GLboolean
function WebGLRenderingContextBase:depthMask(flag) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/depthRange)
---@param zNear GLclampf
---@param zFar GLclampf
function WebGLRenderingContextBase:depthRange(zNear, zFar) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/detachShader)
---@param program WebGLProgram
---@param shader WebGLShader
function WebGLRenderingContextBase:detachShader(program, shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/disable)
---@param cap GLenum
function WebGLRenderingContextBase:disable(cap) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/disableVertexAttribArray)
---@param index GLuint
function WebGLRenderingContextBase:disableVertexAttribArray(index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawArrays)
---@param mode GLenum
---@param first GLint
---@param count GLsizei
function WebGLRenderingContextBase:drawArrays(mode, first, count) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/drawElements)
---@param mode GLenum
---@param count GLsizei
---@param type GLenum
---@param offset GLintptr
function WebGLRenderingContextBase:drawElements(mode, count, type, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/enable)
---@param cap GLenum
function WebGLRenderingContextBase:enable(cap) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/enableVertexAttribArray)
---@param index GLuint
function WebGLRenderingContextBase:enableVertexAttribArray(index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/finish)
function WebGLRenderingContextBase:finish() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/flush)
function WebGLRenderingContextBase:flush() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/framebufferRenderbuffer)
---@param target GLenum
---@param attachment GLenum
---@param renderbuffertarget GLenum
---@param renderbuffer WebGLRenderbuffer|nil
function WebGLRenderingContextBase:framebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/framebufferTexture2D)
---@param target GLenum
---@param attachment GLenum
---@param textarget GLenum
---@param texture WebGLTexture|nil
---@param level GLint
function WebGLRenderingContextBase:framebufferTexture2D(target, attachment, textarget, texture, level) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/frontFace)
---@param mode GLenum
function WebGLRenderingContextBase:frontFace(mode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/generateMipmap)
---@param target GLenum
function WebGLRenderingContextBase:generateMipmap(target) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getActiveAttrib)
---@param program WebGLProgram
---@param index GLuint
---@return WebGLActiveInfo|nil
function WebGLRenderingContextBase:getActiveAttrib(program, index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getActiveUniform)
---@param program WebGLProgram
---@param index GLuint
---@return WebGLActiveInfo|nil
function WebGLRenderingContextBase:getActiveUniform(program, index) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getAttachedShaders)
---@param program WebGLProgram
---@return WebGLShader[]|nil
function WebGLRenderingContextBase:getAttachedShaders(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getAttribLocation)
---@param program WebGLProgram
---@param name string
---@return GLint
function WebGLRenderingContextBase:getAttribLocation(program, name) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getBufferParameter)
---@param target GLenum
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getBufferParameter(target, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getParameter)
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getParameter(pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getError)
---@return GLenum
function WebGLRenderingContextBase:getError() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getFramebufferAttachmentParameter)
---@param target GLenum
---@param attachment GLenum
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getFramebufferAttachmentParameter(target, attachment, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getProgramParameter)
---@param program WebGLProgram
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getProgramParameter(program, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getProgramInfoLog)
---@param program WebGLProgram
---@return string|nil
function WebGLRenderingContextBase:getProgramInfoLog(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getRenderbufferParameter)
---@param target GLenum
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getRenderbufferParameter(target, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getShaderParameter)
---@param shader WebGLShader
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getShaderParameter(shader, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getShaderPrecisionFormat)
---@param shadertype GLenum
---@param precisiontype GLenum
---@return WebGLShaderPrecisionFormat|nil
function WebGLRenderingContextBase:getShaderPrecisionFormat(shadertype, precisiontype) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getShaderInfoLog)
---@param shader WebGLShader
---@return string|nil
function WebGLRenderingContextBase:getShaderInfoLog(shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getShaderSource)
---@param shader WebGLShader
---@return string|nil
function WebGLRenderingContextBase:getShaderSource(shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getTexParameter)
---@param target GLenum
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getTexParameter(target, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getUniform)
---@param program WebGLProgram
---@param location WebGLUniformLocation
---@return any
function WebGLRenderingContextBase:getUniform(program, location) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getUniformLocation)
---@param program WebGLProgram
---@param name string
---@return WebGLUniformLocation|nil
function WebGLRenderingContextBase:getUniformLocation(program, name) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getVertexAttrib)
---@param index GLuint
---@param pname GLenum
---@return any
function WebGLRenderingContextBase:getVertexAttrib(index, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/getVertexAttribOffset)
---@param index GLuint
---@param pname GLenum
---@return GLintptr
function WebGLRenderingContextBase:getVertexAttribOffset(index, pname) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/hint)
---@param target GLenum
---@param mode GLenum
function WebGLRenderingContextBase:hint(target, mode) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isBuffer)
---@param buffer WebGLBuffer|nil
---@return GLboolean
function WebGLRenderingContextBase:isBuffer(buffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isEnabled)
---@param cap GLenum
---@return GLboolean
function WebGLRenderingContextBase:isEnabled(cap) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isFramebuffer)
---@param framebuffer WebGLFramebuffer|nil
---@return GLboolean
function WebGLRenderingContextBase:isFramebuffer(framebuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isProgram)
---@param program WebGLProgram|nil
---@return GLboolean
function WebGLRenderingContextBase:isProgram(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isRenderbuffer)
---@param renderbuffer WebGLRenderbuffer|nil
---@return GLboolean
function WebGLRenderingContextBase:isRenderbuffer(renderbuffer) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isShader)
---@param shader WebGLShader|nil
---@return GLboolean
function WebGLRenderingContextBase:isShader(shader) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/isTexture)
---@param texture WebGLTexture|nil
---@return GLboolean
function WebGLRenderingContextBase:isTexture(texture) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/lineWidth)
---@param width GLfloat
function WebGLRenderingContextBase:lineWidth(width) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/linkProgram)
---@param program WebGLProgram
function WebGLRenderingContextBase:linkProgram(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/pixelStorei)
---@param pname GLenum
---@param param GLint
function WebGLRenderingContextBase:pixelStorei(pname, param) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/polygonOffset)
---@param factor GLfloat
---@param units GLfloat
function WebGLRenderingContextBase:polygonOffset(factor, units) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/renderbufferStorage)
---@param target GLenum
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
function WebGLRenderingContextBase:renderbufferStorage(target, internalformat, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/sampleCoverage)
---@param value GLclampf
---@param invert GLboolean
function WebGLRenderingContextBase:sampleCoverage(value, invert) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/scissor)
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
function WebGLRenderingContextBase:scissor(x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/shaderSource)
---@param shader WebGLShader
---@param source string
function WebGLRenderingContextBase:shaderSource(shader, source) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilFunc)
---@param func GLenum
---@param ref GLint
---@param mask GLuint
function WebGLRenderingContextBase:stencilFunc(func, ref, mask) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilFuncSeparate)
---@param face GLenum
---@param func GLenum
---@param ref GLint
---@param mask GLuint
function WebGLRenderingContextBase:stencilFuncSeparate(face, func, ref, mask) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilMask)
---@param mask GLuint
function WebGLRenderingContextBase:stencilMask(mask) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilMaskSeparate)
---@param face GLenum
---@param mask GLuint
function WebGLRenderingContextBase:stencilMaskSeparate(face, mask) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilOp)
---@param fail GLenum
---@param zfail GLenum
---@param zpass GLenum
function WebGLRenderingContextBase:stencilOp(fail, zfail, zpass) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/stencilOpSeparate)
---@param face GLenum
---@param fail GLenum
---@param zfail GLenum
---@param zpass GLenum
function WebGLRenderingContextBase:stencilOpSeparate(face, fail, zfail, zpass) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/texParameterf)
---@param target GLenum
---@param pname GLenum
---@param param GLfloat
function WebGLRenderingContextBase:texParameterf(target, pname, param) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/texParameteri)
---@param target GLenum
---@param pname GLenum
---@param param GLint
function WebGLRenderingContextBase:texParameteri(target, pname, param) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform1f)
---@param location WebGLUniformLocation|nil
---@param x GLfloat
function WebGLRenderingContextBase:uniform1f(location, x) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform2f)
---@param location WebGLUniformLocation|nil
---@param x GLfloat
---@param y GLfloat
function WebGLRenderingContextBase:uniform2f(location, x, y) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform3f)
---@param location WebGLUniformLocation|nil
---@param x GLfloat
---@param y GLfloat
---@param z GLfloat
function WebGLRenderingContextBase:uniform3f(location, x, y, z) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform4f)
---@param location WebGLUniformLocation|nil
---@param x GLfloat
---@param y GLfloat
---@param z GLfloat
---@param w GLfloat
function WebGLRenderingContextBase:uniform4f(location, x, y, z, w) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform1i)
---@param location WebGLUniformLocation|nil
---@param x GLint
function WebGLRenderingContextBase:uniform1i(location, x) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform2i)
---@param location WebGLUniformLocation|nil
---@param x GLint
---@param y GLint
function WebGLRenderingContextBase:uniform2i(location, x, y) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform3i)
---@param location WebGLUniformLocation|nil
---@param x GLint
---@param y GLint
---@param z GLint
function WebGLRenderingContextBase:uniform3i(location, x, y, z) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform4i)
---@param location WebGLUniformLocation|nil
---@param x GLint
---@param y GLint
---@param z GLint
---@param w GLint
function WebGLRenderingContextBase:uniform4i(location, x, y, z, w) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/useProgram)
---@param program WebGLProgram|nil
function WebGLRenderingContextBase:useProgram(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/validateProgram)
---@param program WebGLProgram
function WebGLRenderingContextBase:validateProgram(program) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib1f)
---@param index GLuint
---@param x GLfloat
function WebGLRenderingContextBase:vertexAttrib1f(index, x) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib2f)
---@param index GLuint
---@param x GLfloat
---@param y GLfloat
function WebGLRenderingContextBase:vertexAttrib2f(index, x, y) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib3f)
---@param index GLuint
---@param x GLfloat
---@param y GLfloat
---@param z GLfloat
function WebGLRenderingContextBase:vertexAttrib3f(index, x, y, z) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib4f)
---@param index GLuint
---@param x GLfloat
---@param y GLfloat
---@param z GLfloat
---@param w GLfloat
function WebGLRenderingContextBase:vertexAttrib4f(index, x, y, z, w) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib1fv)
---@param index GLuint
---@param values Float32List
function WebGLRenderingContextBase:vertexAttrib1fv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib2fv)
---@param index GLuint
---@param values Float32List
function WebGLRenderingContextBase:vertexAttrib2fv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib3fv)
---@param index GLuint
---@param values Float32List
function WebGLRenderingContextBase:vertexAttrib3fv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttrib4fv)
---@param index GLuint
---@param values Float32List
function WebGLRenderingContextBase:vertexAttrib4fv(index, values) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/vertexAttribPointer)
---@param index GLuint
---@param size GLint
---@param type GLenum
---@param normalized GLboolean
---@param stride GLsizei
---@param offset GLintptr
function WebGLRenderingContextBase:vertexAttribPointer(index, size, type, normalized, stride, offset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/viewport)
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
function WebGLRenderingContextBase:viewport(x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext) (members shared by the interfaces that include it)
---@class WebGLRenderingContextOverloads
local WebGLRenderingContextOverloads = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bufferData)
---@param target GLenum
---@param size GLsizeiptr
---@param usage GLenum
---@overload fun(self: WebGLRenderingContextOverloads, target: GLenum, data: AllowSharedBufferSource|nil, usage: GLenum)
function WebGLRenderingContextOverloads:bufferData(target, size, usage) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/bufferSubData)
---@param target GLenum
---@param offset GLintptr
---@param data AllowSharedBufferSource
function WebGLRenderingContextOverloads:bufferSubData(target, offset, data) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/compressedTexImage2D)
---@param target GLenum
---@param level GLint
---@param internalformat GLenum
---@param width GLsizei
---@param height GLsizei
---@param border GLint
---@param data ArrayBufferView
function WebGLRenderingContextOverloads:compressedTexImage2D(target, level, internalformat, width, height, border, data) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/compressedTexSubImage2D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param data ArrayBufferView
function WebGLRenderingContextOverloads:compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, data) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/readPixels)
---@param x GLint
---@param y GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param type GLenum
---@param pixels ArrayBufferView|nil
function WebGLRenderingContextOverloads:readPixels(x, y, width, height, format, type, pixels) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/texImage2D)
---@param target GLenum
---@param level GLint
---@param internalformat GLint
---@param width GLsizei
---@param height GLsizei
---@param border GLint
---@param format GLenum
---@param type GLenum
---@param pixels ArrayBufferView|nil
---@overload fun(self: WebGLRenderingContextOverloads, target: GLenum, level: GLint, internalformat: GLint, format: GLenum, type: GLenum, source: TexImageSource)
function WebGLRenderingContextOverloads:texImage2D(target, level, internalformat, width, height, border, format, type, pixels) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/texSubImage2D)
---@param target GLenum
---@param level GLint
---@param xoffset GLint
---@param yoffset GLint
---@param width GLsizei
---@param height GLsizei
---@param format GLenum
---@param type GLenum
---@param pixels ArrayBufferView|nil
---@overload fun(self: WebGLRenderingContextOverloads, target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, format: GLenum, type: GLenum, source: TexImageSource)
function WebGLRenderingContextOverloads:texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform1fv)
---@param location WebGLUniformLocation|nil
---@param v Float32List
function WebGLRenderingContextOverloads:uniform1fv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform2fv)
---@param location WebGLUniformLocation|nil
---@param v Float32List
function WebGLRenderingContextOverloads:uniform2fv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform3fv)
---@param location WebGLUniformLocation|nil
---@param v Float32List
function WebGLRenderingContextOverloads:uniform3fv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform4fv)
---@param location WebGLUniformLocation|nil
---@param v Float32List
function WebGLRenderingContextOverloads:uniform4fv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform1iv)
---@param location WebGLUniformLocation|nil
---@param v Int32List
function WebGLRenderingContextOverloads:uniform1iv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform2iv)
---@param location WebGLUniformLocation|nil
---@param v Int32List
function WebGLRenderingContextOverloads:uniform2iv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform3iv)
---@param location WebGLUniformLocation|nil
---@param v Int32List
function WebGLRenderingContextOverloads:uniform3iv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniform4iv)
---@param location WebGLUniformLocation|nil
---@param v Int32List
function WebGLRenderingContextOverloads:uniform4iv(location, v) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniformMatrix2fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param value Float32List
function WebGLRenderingContextOverloads:uniformMatrix2fv(location, transpose, value) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniformMatrix3fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param value Float32List
function WebGLRenderingContextOverloads:uniformMatrix3fv(location, transpose, value) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/uniformMatrix4fv)
---@param location WebGLUniformLocation|nil
---@param transpose GLboolean
---@param value Float32List
function WebGLRenderingContextOverloads:uniformMatrix4fv(location, transpose, value) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLSampler)
---@class WebGLSampler : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLShader)
---@class WebGLShader : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLShaderPrecisionFormat)
---@class WebGLShaderPrecisionFormat
---@field rangeMin GLint Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLShaderPrecisionFormat/rangeMin)
---@field rangeMax GLint Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLShaderPrecisionFormat/rangeMax)
---@field precision GLint Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/WebGLShaderPrecisionFormat/precision)

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLSync)
---@class WebGLSync : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLTexture)
---@class WebGLTexture : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLTransformFeedback)
---@class WebGLTransformFeedback : WebGLObject

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLUniformLocation)
---@class WebGLUniformLocation

--- [MDN](https://developer.mozilla.org/docs/Web/API/WebGLVertexArrayObject)
---@class WebGLVertexArrayObject : WebGLObject
