---@meta
-- WebGPU for Lua components, generated by dom/webidl/generate.mjs from the
-- specifications' WebIDL (dom/webidl/idl). Do not edit by hand.
-- Start from `canvas.webgpu()` (hydronium_dom.canvas): `gpu`, the usage flags, and `canvas.context(ref, "webgpu")`. Descriptors are ordinary Lua tables. `end` is a Lua keyword: call `pass["end"](pass)`.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPU)
---@class GPU
---@field wgslLanguageFeatures WGSLLanguageFeatures Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPU/wgslLanguageFeatures)
local GPU = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPU/requestAdapter)
--- Suspends the calling Lua task until the promise settles.
---@param options? GPURequestAdapterOptions Default {}.
---@return GPUAdapter|nil
function GPU:requestAdapter(options) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPU/getPreferredCanvasFormat)
---@return GPUTextureFormat
function GPU:getPreferredCanvasFormat() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapter)
---@class GPUAdapter
---@field features GPUSupportedFeatures Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapter/features)
---@field limits GPUSupportedLimits Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapter/limits)
---@field info GPUAdapterInfo Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapter/info)
local GPUAdapter = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapter/requestDevice)
--- Suspends the calling Lua task until the promise settles.
---@param descriptor? GPUDeviceDescriptor Default {}.
---@return GPUDevice
function GPUAdapter:requestDevice(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo)
---@class GPUAdapterInfo
---@field vendor string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/vendor)
---@field architecture string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/architecture)
---@field device string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/device)
---@field description string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/description)
---@field subgroupMinSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/subgroupMinSize)
---@field subgroupMaxSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/subgroupMaxSize)
---@field isFallbackAdapter boolean Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUAdapterInfo/isFallbackAdapter)

---@alias GPUAddressMode
---| "clamp-to-edge"
---| "repeat"
---| "mirror-repeat"

---@alias GPUAutoLayoutMode
---| "auto"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBindGroup)
---@class GPUBindGroup : GPUObjectBase

---@class GPUBindGroupDescriptor : GPUObjectDescriptorBase
---@field layout GPUBindGroupLayout Required.
---@field entries GPUBindGroupEntry[] Required.

---@class GPUBindGroupEntry
---@field binding GPUIndex32 Required.
---@field resource GPUBindingResource Required.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBindGroupLayout)
---@class GPUBindGroupLayout : GPUObjectBase

---@class GPUBindGroupLayoutDescriptor : GPUObjectDescriptorBase
---@field entries GPUBindGroupLayoutEntry[] Required.

---@class GPUBindGroupLayoutEntry
---@field binding GPUIndex32 Required.
---@field visibility GPUShaderStageFlags Required.
---@field buffer? GPUBufferBindingLayout
---@field sampler? GPUSamplerBindingLayout
---@field texture? GPUTextureBindingLayout
---@field storageTexture? GPUStorageTextureBindingLayout
---@field externalTexture? GPUExternalTextureBindingLayout

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder) (members shared by the interfaces that include it)
---@class GPUBindingCommandsMixin
local GPUBindingCommandsMixin = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setBindGroup)
---@param index GPUIndex32
---@param bindGroup GPUBindGroup|nil
---@param dynamicOffsets? GPUBufferDynamicOffset[] Default {}.
---@overload fun(self: GPUBindingCommandsMixin, index: GPUIndex32, bindGroup: GPUBindGroup|nil, dynamicOffsetsData: Uint32Array, dynamicOffsetsDataStart: GPUSize64, dynamicOffsetsDataLength: GPUSize32)
function GPUBindingCommandsMixin:setBindGroup(index, bindGroup, dynamicOffsets) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setImmediates)
---@param rangeOffset GPUSize32
---@param data AllowSharedBufferSource
---@param dataOffset? GPUSize64 Default 0.
---@param dataSize? GPUSize64
function GPUBindingCommandsMixin:setImmediates(rangeOffset, data, dataOffset, dataSize) end

---@alias GPUBindingResource GPUSampler|GPUTexture|GPUTextureView|GPUBuffer|GPUBufferBinding|GPUExternalTexture

---@class GPUBlendComponent
---@field operation? GPUBlendOperation Default "add".
---@field srcFactor? GPUBlendFactor Default "one".
---@field dstFactor? GPUBlendFactor Default "zero".

---@alias GPUBlendFactor
---| "zero"
---| "one"
---| "src"
---| "one-minus-src"
---| "src-alpha"
---| "one-minus-src-alpha"
---| "dst"
---| "one-minus-dst"
---| "dst-alpha"
---| "one-minus-dst-alpha"
---| "src-alpha-saturated"
---| "constant"
---| "one-minus-constant"
---| "src1"
---| "one-minus-src1"
---| "src1-alpha"
---| "one-minus-src1-alpha"

---@alias GPUBlendOperation
---| "add"
---| "subtract"
---| "reverse-subtract"
---| "min"
---| "max"

---@class GPUBlendState
---@field color GPUBlendComponent Required.
---@field alpha GPUBlendComponent Required.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer)
---@class GPUBuffer : GPUObjectBase
---@field size GPUSize64Out Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/size)
---@field usage GPUFlagsConstant Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/usage)
---@field mapState GPUBufferMapState Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/mapState)
local GPUBuffer = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/mapAsync)
--- Suspends the calling Lua task until the promise settles.
---@param mode GPUMapModeFlags
---@param offset? GPUSize64 Default 0.
---@param size? GPUSize64
function GPUBuffer:mapAsync(mode, offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/getMappedRange)
---@param offset? GPUSize64 Default 0.
---@param size? GPUSize64
---@return ArrayBuffer
function GPUBuffer:getMappedRange(offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/unmap)
function GPUBuffer:unmap() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/destroy)
function GPUBuffer:destroy() end

---@class GPUBufferBinding
---@field buffer GPUBuffer Required.
---@field offset? GPUSize64 Default 0.
---@field size? GPUSize64

---@class GPUBufferBindingLayout
---@field type? GPUBufferBindingType Default "uniform".
---@field hasDynamicOffset? boolean Default false.
---@field minBindingSize? GPUSize64 Default 0.

---@alias GPUBufferBindingType
---| "uniform"
---| "storage"
---| "read-only-storage"

---@class GPUBufferDescriptor : GPUObjectDescriptorBase
---@field size GPUSize64 Required.
---@field usage GPUBufferUsageFlags Required.
---@field mappedAtCreation? boolean Default false.

---@alias GPUBufferDynamicOffset integer

---@alias GPUBufferMapState
---| "unmapped"
---| "pending"
---| "mapped"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBufferUsage) (a namespace of constants)
---@class GPUBufferUsage
---@field MAP_READ integer 0x0001
---@field MAP_WRITE integer 0x0002
---@field COPY_SRC integer 0x0004
---@field COPY_DST integer 0x0008
---@field INDEX integer 0x0010
---@field VERTEX integer 0x0020
---@field UNIFORM integer 0x0040
---@field STORAGE integer 0x0080
---@field INDIRECT integer 0x0100
---@field QUERY_RESOLVE integer 0x0200

---@alias GPUBufferUsageFlags integer

---@alias GPUCanvasAlphaMode
---| "opaque"
---| "premultiplied"

---@class GPUCanvasConfiguration
---@field device GPUDevice Required.
---@field format GPUTextureFormat Required.
---@field usage? GPUTextureUsageFlags Default 0x10.
---@field viewFormats? GPUTextureFormat[] Default {}.
---@field colorSpace? PredefinedColorSpace Default "srgb".
---@field toneMapping? GPUCanvasToneMapping Default {}.
---@field alphaMode? GPUCanvasAlphaMode Default "opaque".

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext)
---@class GPUCanvasContext
---@field canvas HTMLCanvasElement|OffscreenCanvas Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext/canvas)
local GPUCanvasContext = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext/configure)
---@param configuration GPUCanvasConfiguration
function GPUCanvasContext:configure(configuration) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext/unconfigure)
function GPUCanvasContext:unconfigure() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext/getConfiguration)
---@return GPUCanvasConfiguration|nil
function GPUCanvasContext:getConfiguration() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCanvasContext/getCurrentTexture)
---@return GPUTexture
function GPUCanvasContext:getCurrentTexture() end

---@class GPUCanvasToneMapping
---@field mode? GPUCanvasToneMappingMode Default "standard".

---@alias GPUCanvasToneMappingMode
---| "standard"
---| "extended"

---@alias GPUColor number[]|GPUColorDict

---@class GPUColorDict
---@field r number Required.
---@field g number Required.
---@field b number Required.
---@field a number Required.

---@class GPUColorTargetState
---@field format GPUTextureFormat Required.
---@field blend? GPUBlendState
---@field writeMask? GPUColorWriteFlags Default 0xF.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUColorWrite) (a namespace of constants)
---@class GPUColorWrite
---@field RED integer 0x1
---@field GREEN integer 0x2
---@field BLUE integer 0x4
---@field ALPHA integer 0x8
---@field ALL integer 0xF

---@alias GPUColorWriteFlags integer

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandBuffer)
---@class GPUCommandBuffer : GPUObjectBase

---@class GPUCommandBufferDescriptor : GPUObjectDescriptorBase

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder)
---@class GPUCommandEncoder : GPUObjectBase, GPUCommandsMixin, GPUDebugCommandsMixin
local GPUCommandEncoder = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/beginRenderPass)
---@param descriptor GPURenderPassDescriptor
---@return GPURenderPassEncoder
function GPUCommandEncoder:beginRenderPass(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/beginComputePass)
---@param descriptor? GPUComputePassDescriptor Default {}.
---@return GPUComputePassEncoder
function GPUCommandEncoder:beginComputePass(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/copyBufferToBuffer)
---@param source GPUBuffer
---@param destination GPUBuffer
---@param size? GPUSize64
---@overload fun(self: GPUCommandEncoder, source: GPUBuffer, sourceOffset: GPUSize64, destination: GPUBuffer, destinationOffset: GPUSize64, size?: GPUSize64)
function GPUCommandEncoder:copyBufferToBuffer(source, destination, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/copyBufferToTexture)
---@param source GPUTexelCopyBufferInfo
---@param destination GPUTexelCopyTextureInfo
---@param copySize GPUExtent3D
function GPUCommandEncoder:copyBufferToTexture(source, destination, copySize) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/copyTextureToBuffer)
---@param source GPUTexelCopyTextureInfo
---@param destination GPUTexelCopyBufferInfo
---@param copySize GPUExtent3D
function GPUCommandEncoder:copyTextureToBuffer(source, destination, copySize) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/copyTextureToTexture)
---@param source GPUTexelCopyTextureInfo
---@param destination GPUTexelCopyTextureInfo
---@param copySize GPUExtent3D
function GPUCommandEncoder:copyTextureToTexture(source, destination, copySize) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/clearBuffer)
---@param buffer GPUBuffer
---@param offset? GPUSize64 Default 0.
---@param size? GPUSize64
function GPUCommandEncoder:clearBuffer(buffer, offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/resolveQuerySet)
---@param querySet GPUQuerySet
---@param firstQuery GPUSize32
---@param queryCount GPUSize32
---@param destination GPUBuffer
---@param destinationOffset GPUSize64
function GPUCommandEncoder:resolveQuerySet(querySet, firstQuery, queryCount, destination, destinationOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/finish)
---@param descriptor? GPUCommandBufferDescriptor Default {}.
---@return GPUCommandBuffer
function GPUCommandEncoder:finish(descriptor) end

---@class GPUCommandEncoderDescriptor : GPUObjectDescriptorBase

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder) (members shared by the interfaces that include it)
---@class GPUCommandsMixin

---@alias GPUCompareFunction
---| "never"
---| "less"
---| "equal"
---| "less-equal"
---| "greater"
---| "not-equal"
---| "greater-equal"
---| "always"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationInfo)
---@class GPUCompilationInfo
---@field messages GPUCompilationMessage[] Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationInfo/messages)

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage)
---@class GPUCompilationMessage
---@field message string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/message)
---@field type GPUCompilationMessageType Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/type)
---@field lineNum integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/lineNum)
---@field linePos integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/linePos)
---@field offset integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/offset)
---@field length integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUCompilationMessage/length)

---@alias GPUCompilationMessageType
---| "error"
---| "warning"
---| "info"

---@class GPUComputePassDescriptor : GPUObjectDescriptorBase
---@field timestampWrites? GPUComputePassTimestampWrites

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePassEncoder)
---@class GPUComputePassEncoder : GPUObjectBase, GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin
local GPUComputePassEncoder = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePassEncoder/setPipeline)
---@param pipeline GPUComputePipeline
function GPUComputePassEncoder:setPipeline(pipeline) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePassEncoder/dispatchWorkgroups)
---@param workgroupCountX GPUSize32
---@param workgroupCountY? GPUSize32 Default 1.
---@param workgroupCountZ? GPUSize32 Default 1.
function GPUComputePassEncoder:dispatchWorkgroups(workgroupCountX, workgroupCountY, workgroupCountZ) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePassEncoder/dispatchWorkgroupsIndirect)
---@param indirectBuffer GPUBuffer
---@param indirectOffset GPUSize64
function GPUComputePassEncoder:dispatchWorkgroupsIndirect(indirectBuffer, indirectOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePassEncoder/end)
GPUComputePassEncoder["end"] = function(self) end

---@class GPUComputePassTimestampWrites
---@field querySet GPUQuerySet Required.
---@field beginningOfPassWriteIndex? GPUSize32
---@field endOfPassWriteIndex? GPUSize32

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUComputePipeline)
---@class GPUComputePipeline : GPUObjectBase, GPUPipelineBase

---@class GPUComputePipelineDescriptor : GPUPipelineDescriptorBase
---@field compute GPUProgrammableStage Required.

---@class GPUCopyExternalImageDestInfo : GPUTexelCopyTextureInfo
---@field colorSpace? PredefinedColorSpace Default "srgb".
---@field premultipliedAlpha? boolean Default false.

---@alias GPUCopyExternalImageSource ImageBitmap|ImageData|HTMLImageElement|HTMLVideoElement|any|HTMLCanvasElement|OffscreenCanvas

---@class GPUCopyExternalImageSourceInfo
---@field source GPUCopyExternalImageSource Required.
---@field origin? GPUOrigin2D Default {}.
---@field flipY? boolean Default false.

---@alias GPUCullMode
---| "none"
---| "front"
---| "back"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder) (members shared by the interfaces that include it)
---@class GPUDebugCommandsMixin
local GPUDebugCommandsMixin = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/pushDebugGroup)
---@param groupLabel string
function GPUDebugCommandsMixin:pushDebugGroup(groupLabel) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/popDebugGroup)
function GPUDebugCommandsMixin:popDebugGroup() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUCommandEncoder/insertDebugMarker)
---@param markerLabel string
function GPUDebugCommandsMixin:insertDebugMarker(markerLabel) end

---@alias GPUDepthBias integer

---@class GPUDepthStencilState
---@field format GPUTextureFormat Required.
---@field depthWriteEnabled? boolean
---@field depthCompare? GPUCompareFunction
---@field stencilFront? GPUStencilFaceState Default {}.
---@field stencilBack? GPUStencilFaceState Default {}.
---@field stencilReadMask? GPUStencilValue Default 0xFFFFFFFF.
---@field stencilWriteMask? GPUStencilValue Default 0xFFFFFFFF.
---@field depthBias? GPUDepthBias Default 0.
---@field depthBiasSlopeScale? number Default 0.
---@field depthBiasClamp? number Default 0.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice)
---@class GPUDevice : GPUObjectBase
---@field features GPUSupportedFeatures Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/features)
---@field limits GPUSupportedLimits Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/limits)
---@field adapterInfo GPUAdapterInfo Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/adapterInfo)
---@field queue GPUQueue Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/queue)
---@field lost HostPromise Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/lost)
---@field onuncapturederror EventHandler [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/onuncapturederror)
local GPUDevice = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/destroy)
function GPUDevice:destroy() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createBuffer)
---@param descriptor GPUBufferDescriptor
---@return GPUBuffer
function GPUDevice:createBuffer(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createTexture)
---@param descriptor GPUTextureDescriptor
---@return GPUTexture
function GPUDevice:createTexture(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createSampler)
---@param descriptor? GPUSamplerDescriptor Default {}.
---@return GPUSampler
function GPUDevice:createSampler(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/importExternalTexture)
---@param descriptor GPUExternalTextureDescriptor
---@return GPUExternalTexture
function GPUDevice:importExternalTexture(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createBindGroupLayout)
---@param descriptor GPUBindGroupLayoutDescriptor
---@return GPUBindGroupLayout
function GPUDevice:createBindGroupLayout(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createPipelineLayout)
---@param descriptor GPUPipelineLayoutDescriptor
---@return GPUPipelineLayout
function GPUDevice:createPipelineLayout(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createBindGroup)
---@param descriptor GPUBindGroupDescriptor
---@return GPUBindGroup
function GPUDevice:createBindGroup(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createShaderModule)
---@param descriptor GPUShaderModuleDescriptor
---@return GPUShaderModule
function GPUDevice:createShaderModule(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createComputePipeline)
---@param descriptor GPUComputePipelineDescriptor
---@return GPUComputePipeline
function GPUDevice:createComputePipeline(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createRenderPipeline)
---@param descriptor GPURenderPipelineDescriptor
---@return GPURenderPipeline
function GPUDevice:createRenderPipeline(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createComputePipelineAsync)
--- Suspends the calling Lua task until the promise settles.
---@param descriptor GPUComputePipelineDescriptor
---@return GPUComputePipeline
function GPUDevice:createComputePipelineAsync(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createRenderPipelineAsync)
--- Suspends the calling Lua task until the promise settles.
---@param descriptor GPURenderPipelineDescriptor
---@return GPURenderPipeline
function GPUDevice:createRenderPipelineAsync(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createCommandEncoder)
---@param descriptor? GPUCommandEncoderDescriptor Default {}.
---@return GPUCommandEncoder
function GPUDevice:createCommandEncoder(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createRenderBundleEncoder)
---@param descriptor GPURenderBundleEncoderDescriptor
---@return GPURenderBundleEncoder
function GPUDevice:createRenderBundleEncoder(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/createQuerySet)
---@param descriptor GPUQuerySetDescriptor
---@return GPUQuerySet
function GPUDevice:createQuerySet(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/pushErrorScope)
---@param filter GPUErrorFilter
function GPUDevice:pushErrorScope(filter) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDevice/popErrorScope)
--- Suspends the calling Lua task until the promise settles.
---@return GPUError|nil
function GPUDevice:popErrorScope() end

---@class GPUDeviceDescriptor : GPUObjectDescriptorBase
---@field requiredFeatures? GPUFeatureName[] Default {}.
---@field requiredLimits? table<string, GPUSize64|nil> Default {}.
---@field defaultQueue? GPUQueueDescriptor Default {}.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUDeviceLostInfo)
---@class GPUDeviceLostInfo
---@field reason GPUDeviceLostReason Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDeviceLostInfo/reason)
---@field message string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUDeviceLostInfo/message)

---@alias GPUDeviceLostReason
---| "unknown"
---| "destroyed"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUError)
---@class GPUError
---@field message string Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUError/message)

---@alias GPUErrorFilter
---| "validation"
---| "out-of-memory"
---| "internal"

---@alias GPUExtent3D GPUIntegerCoordinate[]|GPUExtent3DDict

---@class GPUExtent3DDict
---@field width GPUIntegerCoordinate Required.
---@field height? GPUIntegerCoordinate Default 1.
---@field depthOrArrayLayers? GPUIntegerCoordinate Default 1.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUExternalTexture)
---@class GPUExternalTexture : GPUObjectBase

---@class GPUExternalTextureBindingLayout

---@class GPUExternalTextureDescriptor : GPUObjectDescriptorBase
---@field source HTMLVideoElement|any Required.
---@field colorSpace? PredefinedColorSpace Default "srgb".

---@alias GPUFeatureName
---| "atomic-vec2u-min-max"
---| "core-features-and-limits"
---| "depth-clip-control"
---| "depth32float-stencil8"
---| "texture-compression-bc"
---| "texture-compression-bc-sliced-3d"
---| "texture-compression-etc2"
---| "texture-compression-astc"
---| "texture-compression-astc-sliced-3d"
---| "timestamp-query"
---| "indirect-first-instance"
---| "shader-f16"
---| "rg11b10ufloat-renderable"
---| "bgra8unorm-storage"
---| "float32-filterable"
---| "float32-blendable"
---| "clip-distances"
---| "dual-source-blending"
---| "subgroups"
---| "texture-formats-tier1"
---| "texture-formats-tier2"
---| "primitive-index"
---| "texture-component-swizzle"
---| "subgroup-size-control"
---| "texture-compression-unaligned"

---@alias GPUFilterMode
---| "nearest"
---| "linear"

---@alias GPUFlagsConstant integer

---@class GPUFragmentState : GPUProgrammableStage
---@field targets (GPUColorTargetState|nil)[] Required.

---@alias GPUFrontFace
---| "ccw"
---| "cw"

---@alias GPUIndex32 integer

---@alias GPUIndexFormat
---| "uint16"
---| "uint32"

---@alias GPUIntegerCoordinate integer

---@alias GPUIntegerCoordinateOut integer

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUInternalError)
---@class GPUInternalError : GPUError

---@alias GPULoadOp
---| "load"
---| "clear"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUMapMode) (a namespace of constants)
---@class GPUMapMode
---@field READ integer 0x0001
---@field WRITE integer 0x0002

---@alias GPUMapModeFlags integer

---@alias GPUMipmapFilterMode
---| "nearest"
---| "linear"

---@class GPUMultisampleState
---@field count? GPUSize32 Default 1.
---@field mask? GPUSampleMask Default 0xFFFFFFFF.
---@field alphaToCoverageEnabled? boolean Default false.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer) (members shared by the interfaces that include it)
---@class GPUObjectBase
---@field label string [MDN](https://developer.mozilla.org/docs/Web/API/GPUBuffer/label)

---@class GPUObjectDescriptorBase
---@field label? string Default "".

---@alias GPUOrigin2D GPUIntegerCoordinate[]|GPUOrigin2DDict

---@class GPUOrigin2DDict
---@field x? GPUIntegerCoordinate Default 0.
---@field y? GPUIntegerCoordinate Default 0.

---@alias GPUOrigin3D GPUIntegerCoordinate[]|GPUOrigin3DDict

---@class GPUOrigin3DDict
---@field x? GPUIntegerCoordinate Default 0.
---@field y? GPUIntegerCoordinate Default 0.
---@field z? GPUIntegerCoordinate Default 0.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUOutOfMemoryError)
---@class GPUOutOfMemoryError : GPUError

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPipeline) (members shared by the interfaces that include it)
---@class GPUPipelineBase
local GPUPipelineBase = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPipeline/getBindGroupLayout)
---@param index integer
---@return GPUBindGroupLayout
function GPUPipelineBase:getBindGroupLayout(index) end

---@alias GPUPipelineConstantValue number

---@class GPUPipelineDescriptorBase : GPUObjectDescriptorBase
---@field layout GPUPipelineLayout|GPUAutoLayoutMode Required.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUPipelineError)
---@class GPUPipelineError
---@field reason GPUPipelineErrorReason Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUPipelineError/reason)

---@class GPUPipelineErrorInit
---@field reason GPUPipelineErrorReason Required.

---@alias GPUPipelineErrorReason
---| "validation"
---| "internal"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUPipelineLayout)
---@class GPUPipelineLayout : GPUObjectBase

---@class GPUPipelineLayoutDescriptor : GPUObjectDescriptorBase
---@field bindGroupLayouts (GPUBindGroupLayout|nil)[] Required.
---@field immediateSize? GPUSize32 Default 0.

---@alias GPUPowerPreference
---| "low-power"
---| "high-performance"

---@class GPUPrimitiveState
---@field topology? GPUPrimitiveTopology Default "triangle-list".
---@field stripIndexFormat? GPUIndexFormat
---@field frontFace? GPUFrontFace Default "ccw".
---@field cullMode? GPUCullMode Default "none".
---@field unclippedDepth? boolean Default false.

---@alias GPUPrimitiveTopology
---| "point-list"
---| "line-list"
---| "line-strip"
---| "triangle-list"
---| "triangle-strip"

---@class GPUProgrammableStage
---@field module GPUShaderModule Required.
---@field entryPoint? string
---@field constants? table<string, GPUPipelineConstantValue> Default {}.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQuerySet)
---@class GPUQuerySet : GPUObjectBase
---@field type GPUQueryType Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUQuerySet/type)
---@field count GPUSize32Out Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUQuerySet/count)
local GPUQuerySet = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQuerySet/destroy)
function GPUQuerySet:destroy() end

---@class GPUQuerySetDescriptor : GPUObjectDescriptorBase
---@field type GPUQueryType Required.
---@field count GPUSize32 Required.

---@alias GPUQueryType
---| "occlusion"
---| "timestamp"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue)
---@class GPUQueue : GPUObjectBase
local GPUQueue = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue/submit)
---@param commandBuffers GPUCommandBuffer[]
function GPUQueue:submit(commandBuffers) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue/onSubmittedWorkDone)
--- Suspends the calling Lua task until the promise settles.
function GPUQueue:onSubmittedWorkDone() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue/writeBuffer)
---@param buffer GPUBuffer
---@param bufferOffset GPUSize64
---@param data AllowSharedBufferSource
---@param dataOffset? GPUSize64 Default 0.
---@param size? GPUSize64
function GPUQueue:writeBuffer(buffer, bufferOffset, data, dataOffset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue/writeTexture)
---@param destination GPUTexelCopyTextureInfo
---@param data AllowSharedBufferSource
---@param dataLayout GPUTexelCopyBufferLayout
---@param size GPUExtent3D
function GPUQueue:writeTexture(destination, data, dataLayout, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUQueue/copyExternalImageToTexture)
---@param source GPUCopyExternalImageSourceInfo
---@param destination GPUCopyExternalImageDestInfo
---@param copySize GPUExtent3D
function GPUQueue:copyExternalImageToTexture(source, destination, copySize) end

---@class GPUQueueDescriptor : GPUObjectDescriptorBase

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderBundle)
---@class GPURenderBundle : GPUObjectBase

---@class GPURenderBundleDescriptor : GPUObjectDescriptorBase

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderBundleEncoder)
---@class GPURenderBundleEncoder : GPUObjectBase, GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin
local GPURenderBundleEncoder = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderBundleEncoder/finish)
---@param descriptor? GPURenderBundleDescriptor Default {}.
---@return GPURenderBundle
function GPURenderBundleEncoder:finish(descriptor) end

---@class GPURenderBundleEncoderDescriptor : GPURenderPassLayout
---@field depthReadOnly? boolean Default false.
---@field stencilReadOnly? boolean Default false.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder) (members shared by the interfaces that include it)
---@class GPURenderCommandsMixin
local GPURenderCommandsMixin = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setPipeline)
---@param pipeline GPURenderPipeline
function GPURenderCommandsMixin:setPipeline(pipeline) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setIndexBuffer)
---@param buffer GPUBuffer
---@param indexFormat GPUIndexFormat
---@param offset? GPUSize64 Default 0.
---@param size? GPUSize64
function GPURenderCommandsMixin:setIndexBuffer(buffer, indexFormat, offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setVertexBuffer)
---@param slot GPUIndex32
---@param buffer GPUBuffer|nil
---@param offset? GPUSize64 Default 0.
---@param size? GPUSize64
function GPURenderCommandsMixin:setVertexBuffer(slot, buffer, offset, size) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/draw)
---@param vertexCount GPUSize32
---@param instanceCount? GPUSize32 Default 1.
---@param firstVertex? GPUSize32 Default 0.
---@param firstInstance? GPUSize32 Default 0.
function GPURenderCommandsMixin:draw(vertexCount, instanceCount, firstVertex, firstInstance) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/drawIndexed)
---@param indexCount GPUSize32
---@param instanceCount? GPUSize32 Default 1.
---@param firstIndex? GPUSize32 Default 0.
---@param baseVertex? GPUSignedOffset32 Default 0.
---@param firstInstance? GPUSize32 Default 0.
function GPURenderCommandsMixin:drawIndexed(indexCount, instanceCount, firstIndex, baseVertex, firstInstance) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/drawIndirect)
---@param indirectBuffer GPUBuffer
---@param indirectOffset GPUSize64
function GPURenderCommandsMixin:drawIndirect(indirectBuffer, indirectOffset) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/drawIndexedIndirect)
---@param indirectBuffer GPUBuffer
---@param indirectOffset GPUSize64
function GPURenderCommandsMixin:drawIndexedIndirect(indirectBuffer, indirectOffset) end

---@class GPURenderPassColorAttachment
---@field view GPUTexture|GPUTextureView Required.
---@field depthSlice? GPUIntegerCoordinate
---@field resolveTarget? GPUTexture|GPUTextureView
---@field clearValue? GPUColor
---@field loadOp GPULoadOp Required.
---@field storeOp GPUStoreOp Required.

---@class GPURenderPassDepthStencilAttachment
---@field view GPUTexture|GPUTextureView Required.
---@field depthClearValue? number
---@field depthLoadOp? GPULoadOp
---@field depthStoreOp? GPUStoreOp
---@field depthReadOnly? boolean Default false.
---@field stencilClearValue? GPUStencilValue Default 0.
---@field stencilLoadOp? GPULoadOp
---@field stencilStoreOp? GPUStoreOp
---@field stencilReadOnly? boolean Default false.

---@class GPURenderPassDescriptor : GPUObjectDescriptorBase
---@field colorAttachments (GPURenderPassColorAttachment|nil)[] Required.
---@field depthStencilAttachment? GPURenderPassDepthStencilAttachment
---@field occlusionQuerySet? GPUQuerySet
---@field timestampWrites? GPURenderPassTimestampWrites
---@field maxDrawCount? GPUSize64 Default 50000000.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder)
---@class GPURenderPassEncoder : GPUObjectBase, GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin
local GPURenderPassEncoder = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setViewport)
---@param x number
---@param y number
---@param width number
---@param height number
---@param minDepth number
---@param maxDepth number
function GPURenderPassEncoder:setViewport(x, y, width, height, minDepth, maxDepth) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setScissorRect)
---@param x GPUIntegerCoordinate
---@param y GPUIntegerCoordinate
---@param width GPUIntegerCoordinate
---@param height GPUIntegerCoordinate
function GPURenderPassEncoder:setScissorRect(x, y, width, height) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setBlendConstant)
---@param color GPUColor
function GPURenderPassEncoder:setBlendConstant(color) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/setStencilReference)
---@param reference GPUStencilValue
function GPURenderPassEncoder:setStencilReference(reference) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/beginOcclusionQuery)
---@param queryIndex GPUSize32
function GPURenderPassEncoder:beginOcclusionQuery(queryIndex) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/endOcclusionQuery)
function GPURenderPassEncoder:endOcclusionQuery() end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/executeBundles)
---@param bundles GPURenderBundle[]
function GPURenderPassEncoder:executeBundles(bundles) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPassEncoder/end)
GPURenderPassEncoder["end"] = function(self) end

---@class GPURenderPassLayout : GPUObjectDescriptorBase
---@field colorFormats (GPUTextureFormat|nil)[] Required.
---@field depthStencilFormat? GPUTextureFormat
---@field sampleCount? GPUSize32 Default 1.

---@class GPURenderPassTimestampWrites
---@field querySet GPUQuerySet Required.
---@field beginningOfPassWriteIndex? GPUSize32
---@field endOfPassWriteIndex? GPUSize32

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPURenderPipeline)
---@class GPURenderPipeline : GPUObjectBase, GPUPipelineBase

---@class GPURenderPipelineDescriptor : GPUPipelineDescriptorBase
---@field vertex GPUVertexState Required.
---@field primitive? GPUPrimitiveState Default {}.
---@field depthStencil? GPUDepthStencilState
---@field multisample? GPUMultisampleState Default {}.
---@field fragment? GPUFragmentState

---@class GPURequestAdapterOptions
---@field featureLevel? string Default "core".
---@field powerPreference? GPUPowerPreference
---@field forceFallbackAdapter? boolean Default false.
---@field xrCompatible? boolean Default false.

---@alias GPUSampleMask integer

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUSampler)
---@class GPUSampler : GPUObjectBase

---@class GPUSamplerBindingLayout
---@field type? GPUSamplerBindingType Default "filtering".

---@alias GPUSamplerBindingType
---| "filtering"
---| "non-filtering"
---| "comparison"

---@class GPUSamplerDescriptor : GPUObjectDescriptorBase
---@field addressModeU? GPUAddressMode Default "clamp-to-edge".
---@field addressModeV? GPUAddressMode Default "clamp-to-edge".
---@field addressModeW? GPUAddressMode Default "clamp-to-edge".
---@field magFilter? GPUFilterMode Default "nearest".
---@field minFilter? GPUFilterMode Default "nearest".
---@field mipmapFilter? GPUMipmapFilterMode Default "nearest".
---@field lodMinClamp? number Default 0.
---@field lodMaxClamp? number Default 32.
---@field compare? GPUCompareFunction
---@field maxAnisotropy? integer Default 1.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUShaderModule)
---@class GPUShaderModule : GPUObjectBase
local GPUShaderModule = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUShaderModule/getCompilationInfo)
--- Suspends the calling Lua task until the promise settles.
---@return GPUCompilationInfo
function GPUShaderModule:getCompilationInfo() end

---@class GPUShaderModuleCompilationHint
---@field entryPoint string Required.
---@field layout? GPUPipelineLayout|GPUAutoLayoutMode

---@class GPUShaderModuleDescriptor : GPUObjectDescriptorBase
---@field code string Required.
---@field compilationHints? GPUShaderModuleCompilationHint[] Default {}.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUShaderStage) (a namespace of constants)
---@class GPUShaderStage
---@field VERTEX integer 0x1
---@field FRAGMENT integer 0x2
---@field COMPUTE integer 0x4

---@alias GPUShaderStageFlags integer

---@alias GPUSignedOffset32 integer

---@alias GPUSize32 integer

---@alias GPUSize32Out integer

---@alias GPUSize64 integer

---@alias GPUSize64Out integer

---@class GPUStencilFaceState
---@field compare? GPUCompareFunction Default "always".
---@field failOp? GPUStencilOperation Default "keep".
---@field depthFailOp? GPUStencilOperation Default "keep".
---@field passOp? GPUStencilOperation Default "keep".

---@alias GPUStencilOperation
---| "keep"
---| "zero"
---| "replace"
---| "invert"
---| "increment-clamp"
---| "decrement-clamp"
---| "increment-wrap"
---| "decrement-wrap"

---@alias GPUStencilValue integer

---@alias GPUStorageTextureAccess
---| "write-only"
---| "read-only"
---| "read-write"

---@class GPUStorageTextureBindingLayout
---@field access? GPUStorageTextureAccess Default "write-only".
---@field format GPUTextureFormat Required.
---@field viewDimension? GPUTextureViewDimension Default "2d".

---@alias GPUStoreOp
---| "store"
---| "discard"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedFeatures)
---@class GPUSupportedFeatures
---@field size integer
---@field has fun(self: GPUSupportedFeatures, value: string): boolean

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits)
---@class GPUSupportedLimits
---@field maxTextureDimension1D integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxTextureDimension1D)
---@field maxTextureDimension2D integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxTextureDimension2D)
---@field maxTextureDimension3D integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxTextureDimension3D)
---@field maxTextureArrayLayers integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxTextureArrayLayers)
---@field maxBindGroups integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxBindGroups)
---@field maxBindGroupsPlusVertexBuffers integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxBindGroupsPlusVertexBuffers)
---@field maxImmediateSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxImmediateSize)
---@field maxBindingsPerBindGroup integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxBindingsPerBindGroup)
---@field maxDynamicUniformBuffersPerPipelineLayout integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxDynamicUniformBuffersPerPipelineLayout)
---@field maxDynamicStorageBuffersPerPipelineLayout integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxDynamicStorageBuffersPerPipelineLayout)
---@field maxSampledTexturesPerShaderStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxSampledTexturesPerShaderStage)
---@field maxSamplersPerShaderStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxSamplersPerShaderStage)
---@field maxStorageBuffersPerShaderStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageBuffersPerShaderStage)
---@field maxStorageBuffersInVertexStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageBuffersInVertexStage)
---@field maxStorageBuffersInFragmentStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageBuffersInFragmentStage)
---@field maxStorageTexturesPerShaderStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageTexturesPerShaderStage)
---@field maxStorageTexturesInVertexStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageTexturesInVertexStage)
---@field maxStorageTexturesInFragmentStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageTexturesInFragmentStage)
---@field maxUniformBuffersPerShaderStage integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxUniformBuffersPerShaderStage)
---@field maxUniformBufferBindingSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxUniformBufferBindingSize)
---@field maxStorageBufferBindingSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxStorageBufferBindingSize)
---@field minUniformBufferOffsetAlignment integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/minUniformBufferOffsetAlignment)
---@field minStorageBufferOffsetAlignment integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/minStorageBufferOffsetAlignment)
---@field maxVertexBuffers integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxVertexBuffers)
---@field maxBufferSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxBufferSize)
---@field maxVertexAttributes integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxVertexAttributes)
---@field maxVertexBufferArrayStride integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxVertexBufferArrayStride)
---@field maxInterStageShaderVariables integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxInterStageShaderVariables)
---@field maxColorAttachments integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxColorAttachments)
---@field maxColorAttachmentBytesPerSample integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxColorAttachmentBytesPerSample)
---@field maxComputeWorkgroupStorageSize integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeWorkgroupStorageSize)
---@field maxComputeInvocationsPerWorkgroup integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeInvocationsPerWorkgroup)
---@field maxComputeWorkgroupSizeX integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeWorkgroupSizeX)
---@field maxComputeWorkgroupSizeY integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeWorkgroupSizeY)
---@field maxComputeWorkgroupSizeZ integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeWorkgroupSizeZ)
---@field maxComputeWorkgroupsPerDimension integer Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits/maxComputeWorkgroupsPerDimension)

---@class GPUTexelCopyBufferInfo : GPUTexelCopyBufferLayout
---@field buffer GPUBuffer Required.

---@class GPUTexelCopyBufferLayout
---@field offset? GPUSize64 Default 0.
---@field bytesPerRow? GPUSize32
---@field rowsPerImage? GPUSize32

---@class GPUTexelCopyTextureInfo
---@field texture GPUTexture Required.
---@field mipLevel? GPUIntegerCoordinate Default 0.
---@field origin? GPUOrigin3D Default {}.
---@field aspect? GPUTextureAspect Default "all".

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture)
---@class GPUTexture : GPUObjectBase
---@field width GPUIntegerCoordinateOut Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/width)
---@field height GPUIntegerCoordinateOut Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/height)
---@field depthOrArrayLayers GPUIntegerCoordinateOut Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/depthOrArrayLayers)
---@field mipLevelCount GPUIntegerCoordinateOut Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/mipLevelCount)
---@field sampleCount GPUSize32Out Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/sampleCount)
---@field dimension GPUTextureDimension Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/dimension)
---@field format GPUTextureFormat Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/format)
---@field usage GPUFlagsConstant Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/usage)
---@field textureBindingViewDimension GPUTextureViewDimension|nil Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/textureBindingViewDimension)
local GPUTexture = {}

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/createView)
---@param descriptor? GPUTextureViewDescriptor Default {}.
---@return GPUTextureView
function GPUTexture:createView(descriptor) end

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUTexture/destroy)
function GPUTexture:destroy() end

---@alias GPUTextureAspect
---| "all"
---| "stencil-only"
---| "depth-only"

---@class GPUTextureBindingLayout
---@field sampleType? GPUTextureSampleType Default "float".
---@field viewDimension? GPUTextureViewDimension Default "2d".
---@field multisampled? boolean Default false.

---@class GPUTextureDescriptor : GPUObjectDescriptorBase
---@field size GPUExtent3D Required.
---@field mipLevelCount? GPUIntegerCoordinate Default 1.
---@field sampleCount? GPUSize32 Default 1.
---@field dimension? GPUTextureDimension Default "2d".
---@field format GPUTextureFormat Required.
---@field usage GPUTextureUsageFlags Required.
---@field viewFormats? GPUTextureFormat[] Default {}.
---@field textureBindingViewDimension? GPUTextureViewDimension

---@alias GPUTextureDimension
---| "1d"
---| "2d"
---| "3d"

---@alias GPUTextureFormat
---| "r8unorm"
---| "r8snorm"
---| "r8uint"
---| "r8sint"
---| "r16unorm"
---| "r16snorm"
---| "r16uint"
---| "r16sint"
---| "r16float"
---| "rg8unorm"
---| "rg8snorm"
---| "rg8uint"
---| "rg8sint"
---| "r32uint"
---| "r32sint"
---| "r32float"
---| "rg16unorm"
---| "rg16snorm"
---| "rg16uint"
---| "rg16sint"
---| "rg16float"
---| "rgba8unorm"
---| "rgba8unorm-srgb"
---| "rgba8snorm"
---| "rgba8uint"
---| "rgba8sint"
---| "bgra8unorm"
---| "bgra8unorm-srgb"
---| "rgb9e5ufloat"
---| "rgb10a2uint"
---| "rgb10a2unorm"
---| "rg11b10ufloat"
---| "rg32uint"
---| "rg32sint"
---| "rg32float"
---| "rgba16unorm"
---| "rgba16snorm"
---| "rgba16uint"
---| "rgba16sint"
---| "rgba16float"
---| "rgba32uint"
---| "rgba32sint"
---| "rgba32float"
---| "stencil8"
---| "depth16unorm"
---| "depth24plus"
---| "depth24plus-stencil8"
---| "depth32float"
---| "depth32float-stencil8"
---| "bc1-rgba-unorm"
---| "bc1-rgba-unorm-srgb"
---| "bc2-rgba-unorm"
---| "bc2-rgba-unorm-srgb"
---| "bc3-rgba-unorm"
---| "bc3-rgba-unorm-srgb"
---| "bc4-r-unorm"
---| "bc4-r-snorm"
---| "bc5-rg-unorm"
---| "bc5-rg-snorm"
---| "bc6h-rgb-ufloat"
---| "bc6h-rgb-float"
---| "bc7-rgba-unorm"
---| "bc7-rgba-unorm-srgb"
---| "etc2-rgb8unorm"
---| "etc2-rgb8unorm-srgb"
---| "etc2-rgb8a1unorm"
---| "etc2-rgb8a1unorm-srgb"
---| "etc2-rgba8unorm"
---| "etc2-rgba8unorm-srgb"
---| "eac-r11unorm"
---| "eac-r11snorm"
---| "eac-rg11unorm"
---| "eac-rg11snorm"
---| "astc-4x4-unorm"
---| "astc-4x4-unorm-srgb"
---| "astc-5x4-unorm"
---| "astc-5x4-unorm-srgb"
---| "astc-5x5-unorm"
---| "astc-5x5-unorm-srgb"
---| "astc-6x5-unorm"
---| "astc-6x5-unorm-srgb"
---| "astc-6x6-unorm"
---| "astc-6x6-unorm-srgb"
---| "astc-8x5-unorm"
---| "astc-8x5-unorm-srgb"
---| "astc-8x6-unorm"
---| "astc-8x6-unorm-srgb"
---| "astc-8x8-unorm"
---| "astc-8x8-unorm-srgb"
---| "astc-10x5-unorm"
---| "astc-10x5-unorm-srgb"
---| "astc-10x6-unorm"
---| "astc-10x6-unorm-srgb"
---| "astc-10x8-unorm"
---| "astc-10x8-unorm-srgb"
---| "astc-10x10-unorm"
---| "astc-10x10-unorm-srgb"
---| "astc-12x10-unorm"
---| "astc-12x10-unorm-srgb"
---| "astc-12x12-unorm"
---| "astc-12x12-unorm-srgb"

---@alias GPUTextureSampleType
---| "float"
---| "unfilterable-float"
---| "depth"
---| "sint"
---| "uint"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUTextureUsage) (a namespace of constants)
---@class GPUTextureUsage
---@field COPY_SRC integer 0x01
---@field COPY_DST integer 0x02
---@field TEXTURE_BINDING integer 0x04
---@field STORAGE_BINDING integer 0x08
---@field RENDER_ATTACHMENT integer 0x10
---@field TRANSIENT_ATTACHMENT integer 0x20

---@alias GPUTextureUsageFlags integer

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUTextureView)
---@class GPUTextureView : GPUObjectBase

---@class GPUTextureViewDescriptor : GPUObjectDescriptorBase
---@field format? GPUTextureFormat
---@field dimension? GPUTextureViewDimension
---@field usage? GPUTextureUsageFlags Default 0.
---@field aspect? GPUTextureAspect Default "all".
---@field baseMipLevel? GPUIntegerCoordinate Default 0.
---@field mipLevelCount? GPUIntegerCoordinate
---@field baseArrayLayer? GPUIntegerCoordinate Default 0.
---@field arrayLayerCount? GPUIntegerCoordinate
---@field swizzle? string Default "rgba".

---@alias GPUTextureViewDimension
---| "1d"
---| "2d"
---| "2d-array"
---| "cube"
---| "cube-array"
---| "3d"

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUUncapturedErrorEvent)
---@class GPUUncapturedErrorEvent
---@field error GPUError Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/GPUUncapturedErrorEvent/error)

---@class GPUUncapturedErrorEventInit
---@field error GPUError Required.

--- [MDN](https://developer.mozilla.org/docs/Web/API/GPUValidationError)
---@class GPUValidationError : GPUError

---@class GPUVertexAttribute
---@field format GPUVertexFormat Required.
---@field offset GPUSize64 Required.
---@field shaderLocation GPUIndex32 Required.

---@class GPUVertexBufferLayout
---@field arrayStride GPUSize64 Required.
---@field stepMode? GPUVertexStepMode Default "vertex".
---@field attributes GPUVertexAttribute[] Required.

---@alias GPUVertexFormat
---| "uint8"
---| "uint8x2"
---| "uint8x4"
---| "sint8"
---| "sint8x2"
---| "sint8x4"
---| "unorm8"
---| "unorm8x2"
---| "unorm8x4"
---| "snorm8"
---| "snorm8x2"
---| "snorm8x4"
---| "uint16"
---| "uint16x2"
---| "uint16x4"
---| "sint16"
---| "sint16x2"
---| "sint16x4"
---| "unorm16"
---| "unorm16x2"
---| "unorm16x4"
---| "snorm16"
---| "snorm16x2"
---| "snorm16x4"
---| "float16"
---| "float16x2"
---| "float16x4"
---| "float32"
---| "float32x2"
---| "float32x3"
---| "float32x4"
---| "uint32"
---| "uint32x2"
---| "uint32x3"
---| "uint32x4"
---| "sint32"
---| "sint32x2"
---| "sint32x3"
---| "sint32x4"
---| "unorm10-10-10-2"
---| "unorm8x4-bgra"
---| "snorm10-10-10-2"

---@class GPUVertexState : GPUProgrammableStage
---@field buffers? (GPUVertexBufferLayout|nil)[] Default {}.

---@alias GPUVertexStepMode
---| "vertex"
---| "instance"

--- [MDN](https://developer.mozilla.org/docs/Web/API/Navigator) (members shared by the interfaces that include it)
---@class NavigatorGPU
---@field gpu GPU Read-only. [MDN](https://developer.mozilla.org/docs/Web/API/Navigator/gpu)

--- [MDN](https://developer.mozilla.org/docs/Web/API/WGSLLanguageFeatures)
---@class WGSLLanguageFeatures
---@field size integer
---@field has fun(self: WGSLLanguageFeatures, value: string): boolean
