local t=require("tests.runner")
local q=require("hydronium_query")
local remote=require("hydronium_table.remote")
t.describe("remote grids",function()
  t.it("sends full dataset search and sorting to the server and rejects stale replies",function()
    local requests,cancelled={},0
    local grid=remote.create({client=q.createClient(),key="packages",page_size=2,
      columns={{id="name",accessor=function(row)return row.name end}},
      query=function(params,_,done)
        requests[#requests+1]={params=params,done=done}
        return function()cancelled=cancelled+1 end
      end})
    requests[1].done(nil,{rows={{name="z"},{name="a"}},total=9})
    grid.model:toggleSort("name")
    t.assert.equal(requests[2].params.sorting[1].id,"name")
    grid.model:setGlobalFilter("across all rows")
    t.assert.equal(requests[3].params.search,"across all rows")
    requests[2].done(nil,{rows={{name="obsolete"}},total=9})
    t.assert.equal(grid.state().status,"pending")
    requests[3].done(nil,{rows={{name="server order"}},total=5})
    t.assert.equal(grid.model:getRows()[1].cells.name,"server order")
    grid.model:setPage(1)
    t.assert.equal(requests[4].params.page,1)
    grid.model:setGlobalFilter("new")
    t.assert.equal(requests[5].params.page,0)
    grid:dispose();requests[5].done(nil,{rows={},total=0})
    t.assert.truthy(cancelled>0)
  end)
  t.it("surfaces malformed responses and allows retry",function()
    local done
    local grid=remote.create({client=q.createClient(),key="test",query=function(_,_,reply)done=reply end})
    done(nil,{rows={},total=-1});t.assert.equal(grid.state().status,"error")
    grid:refetch();done(nil,{rows={},total=0})
    t.assert.equal(grid.state().status,"success")
    grid:dispose()
  end)
  t.it("retains page totals while fetching and refetches a valid page after deletion",function()
    local requests={}
    local grid=remote.create({client=q.createClient({stale_time=100}),key="shrinking",page_size=2,
      query=function(params,_,done)requests[#requests+1]={params=params,done=done}end})
    requests[1].done(nil,{rows={{id=1}},total=8})
    grid.model:setPage(3)
    t.assert.equal(grid.total(),8)
    requests[2].done(nil,{rows={},total=1})
    t.assert.equal(requests[3].params.page,0)
    requests[3].done(nil,{rows={{id=9}},total=1})
    t.assert.equal(grid.total(),1)
    t.assert.equal(grid.model:page(),0)
    grid:dispose()
  end)
end)
