local t=require("tests.runner")
local auth=require("hydronium_auth")
t.describe("authentication UI flow",function()
  t.it("cancels and ignores stale replies after reset",function()
    local done,cancelled
    local flow=auth.createFlow({transport=function(_,_,reply)done=reply;return function()cancelled=true end end})
    flow:submit("email",{});t.assert.truthy(flow.state().pending)
    t.assert.falsy(flow:submit("email",{}))
    flow:reset();done(nil,{step="complete"})
    t.assert.truthy(cancelled);t.assert.equal(flow.state().step,"credentials")
  end)
  t.it("recovers from transport errors and rejects unknown transitions",function()
    local flow=auth.createFlow({steps={credentials=true,otp=true},transport=function(op,_,done)
      if op=="email"then done(nil,{step="otp"})elseif op=="bad"then done(nil,{step="unknown"})else error("offline")end
    end})
    flow:submit("email",{});t.assert.equal(flow.state().step,"otp")
    flow:submit("bad",{});t.assert.truthy(flow.state().error)
    flow:submit("verify",{});t.assert.falsy(flow.state().pending)
    t.assert.equal(flow.state().error,"Could not complete this request. Please try again.")
    flow:dispose();t.assert.falsy(flow:submit("email",{}))
  end)
  t.it("settles once and cancels a transport invalidated before it returns",function()
    local flow,reply,cancelled
    flow=auth.createFlow({transport=function(_,_,done)
      reply=done;flow:reset()
      return function()cancelled=true end
    end})
    flow:submit("email",{})
    t.assert.truthy(cancelled)
    reply(nil,{step="complete"})
    t.assert.equal(flow.state().step,"credentials")
    local finish
    flow=auth.createFlow({transport=function(_,_,done)finish=done end})
    flow:submit("email",{})
    finish(nil,{step="otp"});finish("late error")
    t.assert.equal(flow.state().step,"otp")
    t.assert.equal(flow.state().error,nil)
  end)
end)
