import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const url=process.env.HYDRONIUM_LAB_URL;
test('packaged mixed catalog mounts DOM and Ink, updates args and preserves DOM state through HMR',{skip:!url,timeout:120000},async t=>{
  const browser=await chromium.launch();t.after(()=>browser.close());
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(url);
  await page.getByRole('button',{name:'Counter / default · dom',exact:true}).click();
  const counter=()=>page.frameLocator('[data-lab-dom-preview]').locator('#counter');
  await counter().waitFor();await counter().click();
  await page.waitForFunction(()=>document.querySelector('[data-lab-rulers]')?.dataset.units==='px');
  await page.getByRole('button',{name:'Preferences',exact:true}).click();
  assert.equal(await page.getByRole('checkbox',{name:'Show rulers (R)',exact:true}).isChecked(),true);
  assert.equal(await page.getByRole('checkbox',{name:'Show canvas hints (H)',exact:true}).isChecked(),true);
  assert.equal(await page.getByRole('checkbox',{name:'Enable snapping',exact:true}).isChecked(),true);
  await page.getByRole('button',{name:'Close preferences',exact:true}).click();
  assert.equal(await page.locator('[data-lab-stage] [data-lab-controls]').count(),0,'story tools no longer consume canvas height');
  assert.equal(await page.locator('[data-lab-story-inspector] [data-lab-controls]').count(),1);
  const hint=await page.locator('[data-lab-hint]').boundingBox(),stageRect=await page.locator('[data-lab-stage]').boundingBox();
  assert.ok(hint.x>=stageRect.x+24,'hint clears the vertical ruler');
  await page.locator('[data-lab-stage]').focus();await page.keyboard.press('r');
  await page.waitForFunction(()=>document.querySelector('[data-lab-ruler-hit]').hidden);
  await page.keyboard.press('r');await page.waitForFunction(()=>!document.querySelector('[data-lab-ruler-hit]').hidden);
  await page.keyboard.press('h');assert.equal(await page.locator('[data-lab-hint]').isVisible(),false);
  await page.keyboard.press('h');assert.equal(await page.locator('[data-lab-hint]').isVisible(),true);
  await page.getByRole('textbox',{name:'label',exact:true}).fill('Edited');
  await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('#counter')?.textContent==='Edited:1');
  const iframe=await page.locator('iframe').getAttribute('src');
  const world=page.locator('[data-lab-dom-preview]').locator('..');
  const beforeZoom=await world.evaluate(el=>el.style.transform);
  await page.getByRole('button',{name:'Zoom in',exact:true}).click();
  assert.notEqual(await world.evaluate(el=>el.style.transform),beforeZoom);
  assert.equal(await world.locator('[data-lab-grid]').count(),1,'grid and preview share the transformed world');
  await page.getByRole('button',{name:'Center canvas',exact:true}).click();
  const stage=await page.locator('[data-lab-stage]').boundingBox();
  await page.mouse.move(stage.x+60,stage.y+60);
  await page.mouse.down();
  await page.mouse.move(stage.x+120,stage.y+100);
  await page.mouse.up();
  assert.match(await world.evaluate(el=>el.style.transform),/translate\(60px, 40px\)/,'panning moves the shared world');
  await page.getByRole('button',{name:'Center canvas',exact:true}).click();
  await page.getByRole('combobox',{name:'Viewport preset',exact:true}).selectOption({label:'Mobile · 390×844'});
  await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.innerWidth===390);
  await page.locator('summary').filter({hasText:'Color & vision'}).click();
  await page.getByRole('combobox',{name:'Color vision simulation',exact:true}).selectOption('deuteranopia');
  await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('#preview').style.filter.includes('deuteranopia'));
  assert.equal(await page.getByRole('combobox',{name:'Terminal color capability'}).isVisible(),false);
  const original=await readFile(process.env.HYDRONIUM_LAB_FIXTURE,'utf8');
  try {
    await writeFile(process.env.HYDRONIUM_LAB_FIXTURE,original.replace(' .. ":" .. count()', ' .. " hot:" .. count()'));
    await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('#counter')?.textContent==='Edited hot:1',null,{timeout:45000});
    assert.equal(await page.locator('iframe').getAttribute('src'),iframe,'HMR retains preview VM');
  } finally { await writeFile(process.env.HYDRONIUM_LAB_FIXTURE,original); }
  await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('#counter')?.textContent==='Edited:1',null,{timeout:45000});
  const originalFrame = await page.locator('[data-lab-dom-preview]').elementHandle();
  await page.getByRole('button',{name:'Counter / alternate · dom',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[data-lab-dom-preview]').contentDocument.querySelector('#counter')?.textContent==='Alternate:0');
  assert.equal(await originalFrame.evaluate(frame => frame === document.querySelector('[data-lab-dom-preview]')),true,'same-renderer selection retains the iframe');
  await page.getByRole('button',{name:'Terminal · ink',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.hydroniumLabPreview);
  await page.getByRole('textbox',{name:'label',exact:true}).fill('Terminal edit');
  await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.hydroniumLabPreview.snapshot().lab.args.label==='Terminal edit');
  await page.waitForFunction(()=>document.querySelector('[data-lab-rulers]')?.dataset.units==='cells');
  assert.equal(await page.getByRole('combobox',{name:'Terminal color capability'}).isVisible(),true);
  await page.getByRole('combobox',{name:'Terminal color capability'}).selectOption('ansi16');
  assert.equal(await page.locator('[data-lab-timeline]').isVisible(),true);
  assert.equal(await page.frameLocator('[data-lab-dom-preview]').locator('[data-lab-stage]').count(),0,'Ink has no nested workspace');
  await page.getByRole('button',{name:'Counter / default · dom',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('#counter')?.textContent==='DOM:0');
  assert.equal(await page.locator('[data-lab-timeline]').isVisible(),false);
  assert.deepEqual(errors,[]);
});

test('rulers, editable guides, snapping, colors and removal survive a packaged Lab restart',{skip:!url,timeout:90000},async t=>{
  const browser=await chromium.launch();t.after(()=>browser.close());
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(url);
  await page.getByRole('button',{name:'Counter / default · dom',exact:true}).click();
  await page.frameLocator('[data-lab-dom-preview]').locator('#counter').waitFor();
  const stage=page.locator('[data-lab-stage]'), box=await stage.boundingBox();
  const world=page.locator('[data-lab-viewport]'), frame=page.locator('[data-lab-dom-preview]');
  const viewport=await frame.boundingBox();
  const ruler=page.locator('[data-lab-rulers]');
  await page.waitForFunction(()=>document.querySelector('[data-lab-rulers]')?.dataset.units==='px');
  const grid=await page.locator('[data-lab-grid]').evaluate(el=>({position:el.style.backgroundPosition,width:el.offsetWidth}));
  const unscaledWidth=await frame.evaluate(el=>el.offsetWidth);
  assert.equal(parseFloat(grid.position),grid.width/2-unscaledWidth/2,'grid and ruler use the same viewport origin');
  const gx=viewport.x-box.x-30,gy=viewport.y-box.y+viewport.height/2;
  await page.mouse.move(box.x+12,box.y+12);await page.mouse.down();
  await page.mouse.move(box.x+gx,box.y+gy);await page.mouse.up();
  assert.equal(await page.locator('[data-lab-guide]').count(),2);
  const vertical=page.locator('.hydronium-lab__guide--x'),horizontal=page.locator('.hydronium-lab__guide--y');
  assert.ok(Math.abs(parseFloat(await vertical.evaluate(el=>el.style.left))-gx)<1);
  await page.mouse.move(box.x+60,box.y+60);await page.mouse.down();
  await page.mouse.move(box.x+34,box.y+60);await page.mouse.up();
  const pan=await world.evaluate(el=>el.style.transform);
  assert.match(pan,/translate\(-30px, 0px\)/,'viewport edge snaps to the placed guide');
  await page.waitForFunction(()=>document.querySelector('[data-lab-rulers]').dataset.snapActive==='false');
  await vertical.click();await page.getByRole('button',{name:'Preferences',exact:true}).click();
  await page.getByRole('checkbox',{name:'Snap to canvas center',exact:true}).uncheck();
  await page.getByRole('checkbox',{name:'Snap to canvas edges',exact:true}).uncheck();
  assert.equal(await page.getByRole('checkbox',{name:'Snap to placed guides',exact:true}).isChecked(),true);
  await page.getByRole('spinbutton',{name:'Snap distance',exact:true}).fill('12');
  await page.getByRole('spinbutton',{name:'Snap distance',exact:true}).press('Tab');
  await page.getByRole('button',{name:'Close preferences',exact:true}).click();
  await page.reload();await page.frameLocator('[data-lab-dom-preview]').locator('#counter').waitFor();
  assert.equal(await page.locator('[data-lab-guide]').count(),2,'placed guides persist');
  await page.getByRole('button',{name:'Preferences',exact:true}).click();
  assert.equal(await page.getByRole('checkbox',{name:'Snap to canvas center',exact:true}).isChecked(),false);
  assert.equal(await page.getByRole('spinbutton',{name:'Snap distance',exact:true}).inputValue(),'12');
  await page.getByRole('button',{name:'Close preferences',exact:true}).click();
  const verticalBox=await vertical.boundingBox();
  await page.mouse.move(verticalBox.x+verticalBox.width/2,box.y+60);await page.mouse.down();
  await page.mouse.move(box.x+12,box.y+12);await page.mouse.up();
  assert.equal(await page.locator('[data-lab-guide]').count(),1,'dragging into corner removes a guide');
  await horizontal.click({modifiers:['Alt']});
  assert.equal(await page.locator('[data-lab-guide]').count(),0,'Alt-click removes a guide');
  assert.deepEqual(errors,[]);
});
