local runner = require("tests.runner")
local dom_typing = require("hydronium.luax.dom_typing")

describe("LUAX DOM Typing Definitions", function()
  local defs = dom_typing.get_dom_definitions()

  it("returns non-empty EmmyLua definitions string", function()
    assert.is_string(defs)
    assert.truthy(#defs > 500, "Definitions string should be substantial")
    assert.truthy(defs:find("---@meta Hydronium LUAX DOM Typings"), "Expected @meta header")
  end)

  describe("Event hierarchy", function()
    it("defines base SyntheticEvent<T> with standard methods and properties", function()
      assert.truthy(defs:find("---@class SyntheticEvent<T>"), "Expected SyntheticEvent<T>")
      assert.truthy(defs:find("---@field target T"), "Expected target field")
      assert.truthy(defs:find("---@field currentTarget T"), "Expected currentTarget field")
      assert.truthy(defs:find("---@field preventDefault fun%(%)"), "Expected preventDefault")
      assert.truthy(defs:find("---@field stopPropagation fun%(%)"), "Expected stopPropagation")
      assert.truthy(defs:find("---@field isDefaultPrevented fun%(%): boolean"), "Expected isDefaultPrevented")
      assert.truthy(defs:find("---@field isPropagationStopped fun%(%): boolean"), "Expected isPropagationStopped")
    end)

    it("defines SyntheticMouseEvent<T> inheriting SyntheticEvent<T>", function()
      assert.truthy(defs:find("---@class SyntheticMouseEvent<T> : SyntheticEvent<T>"))
      assert.truthy(defs:find("---@field clientX number"))
      assert.truthy(defs:find("---@field clientY number"))
      assert.truthy(defs:find("---@field button number"))
      assert.truthy(defs:find("---@field altKey boolean"))
      assert.truthy(defs:find("---@field ctrlKey boolean"))
      assert.truthy(defs:find("---@field metaKey boolean"))
      assert.truthy(defs:find("---@field shiftKey boolean"))
    end)

    it("defines SyntheticKeyboardEvent<T> inheriting SyntheticEvent<T>", function()
      assert.truthy(defs:find("---@class SyntheticKeyboardEvent<T> : SyntheticEvent<T>"))
      assert.truthy(defs:find("---@field key string"))
      assert.truthy(defs:find("---@field code string"))
      assert.truthy(defs:find("---@field repeat boolean"))
    end)

    it("defines SyntheticFocusEvent<T> and SyntheticChangeEvent<T>", function()
      assert.truthy(defs:find("---@class SyntheticFocusEvent<T> : SyntheticEvent<T>"))
      assert.truthy(defs:find("---@class SyntheticChangeEvent<T> : SyntheticEvent<T>"))
      assert.truthy(defs:find("---@field value string"))
    end)
  end)

  describe("Host DOM element hierarchy", function()
    it("defines HTMLElement base and element subtypes", function()
      assert.truthy(defs:find("---@class HTMLElement"))
      assert.truthy(defs:find("---@class HTMLButtonElement : HTMLElement"))
      assert.truthy(defs:find("---@class HTMLInputElement : HTMLElement"))
      assert.truthy(defs:find("---@class HTMLDivElement : HTMLElement"))
      assert.truthy(defs:find("---@class HTMLSpanElement : HTMLElement"))
      assert.truthy(defs:find("---@class HTMLAnchorElement : HTMLElement"))
    end)

    it("defines element-specific fields on host elements", function()
      assert.truthy(defs:find("---@field disabled boolean"))
      assert.truthy(defs:find("---@field href string"))
      assert.truthy(defs:find("---@field placeholder string"))
    end)
  end)

  describe("Element Props and Contextual Callback Typing", function()
    it("defines HTMLAttributes with common JSX props", function()
      assert.truthy(defs:find("---@class HTMLAttributes"))
      assert.truthy(defs:find("---@field id%? string"))
      assert.truthy(defs:find("---@field class%? string"))
      assert.truthy(defs:find("---@field className%? string"))
      assert.truthy(defs:find("---@field key%? string|number"))
      assert.truthy(defs:find("---@field children%? any"))
    end)

    it("contextually types HTMLButtonProps callbacks with SyntheticMouseEvent<HTMLButtonElement>", function()
      assert.truthy(defs:find("---@class HTMLButtonProps : HTMLAttributes"))
      assert.truthy(defs:find("---@field onClick%? fun%(event: SyntheticMouseEvent<HTMLButtonElement>%)"))
    end)

    it("contextually types HTMLInputProps callbacks with SyntheticChangeEvent and SyntheticFocusEvent", function()
      assert.truthy(defs:find("---@class HTMLInputProps : HTMLAttributes"))
      assert.truthy(defs:find("---@field onChange%? fun%(event: SyntheticChangeEvent<HTMLInputElement>%)"))
      assert.truthy(defs:find("---@field onFocus%? fun%(event: SyntheticFocusEvent<HTMLInputElement>%)"))
      assert.truthy(defs:find("---@field onBlur%? fun%(event: SyntheticFocusEvent<HTMLInputElement>%)"))
    end)

    it("defines HTMLDivProps, HTMLSpanProps, and HTMLAnchorProps", function()
      assert.truthy(defs:find("---@class HTMLDivProps : HTMLAttributes"))
      assert.truthy(defs:find("---@class HTMLSpanProps : HTMLAttributes"))
      assert.truthy(defs:find("---@class HTMLAnchorProps : HTMLAttributes"))
      assert.truthy(defs:find("---@field href%? string"))
    end)
  end)

  describe("Intrinsic Catalog and Virtual Lowering Helpers", function()
    it("defines __luax_intrinsic_catalog mapping tag names to prop signatures", function()
      assert.truthy(defs:find("---@class __luax_intrinsic_catalog"))
      assert.truthy(defs:find("---@field button fun%(props%?: HTMLButtonProps"))
      assert.truthy(defs:find("---@field input fun%(props%?: HTMLInputProps"))
      assert.truthy(defs:find("---@field div fun%(props%?: HTMLDivProps"))
      assert.truthy(defs:find("---@field span fun%(props%?: HTMLSpanProps"))
      assert.truthy(defs:find("---@field a fun%(props%?: HTMLAnchorProps"))
    end)

    it("defines __luax_intrinsic global typed variable", function()
      assert.truthy(defs:find("---@type __luax_intrinsic_catalog"))
      assert.truthy(defs:find("__luax_intrinsic = {}"))
    end)

    it("defines __luax_component helper with generic parameter propagation", function()
      assert.truthy(defs:find("---@generic T, P"))
      assert.truthy(defs:find("---@param comp fun%(props: P%): T"))
      assert.truthy(defs:find("function __luax_component%(comp, props, %.%.%.%)"))
    end)

    it("defines __luax_fragment helper", function()
      assert.truthy(defs:find("function __luax_fragment%(%.%.%.%)"))
    end)
  end)

  describe("File Generation", function()
    it("writes definitions to file", function()
      local tmp_path = "tests/fixtures/test_dom_typing.d.lua"
      dom_typing.write_definitions_file(tmp_path)

      local f = io.open(tmp_path, "r")
      assert.is_not_nil(f, "Expected generated definitions file to exist")
      local content = f:read("*a")
      f:close()

      assert.truthy(content:find("---@meta Hydronium LUAX DOM Typings"))
      assert.truthy(content:find("__luax_intrinsic"))

      os.remove(tmp_path)
    end)
  end)
end)
